# Generated by Django 5.0.11 on 2025-08-05 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0011_alter_paciente_fecha_nacimiento_and_more'),
        ('servicio', '0007_serviciosaux'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Clasificación de Estudio',
                'verbose_name_plural': 'Clasificaciones de Estudios',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='MaquinaRX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_maquina', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Descripcion maquina')),
                ('estado', models.BooleanField(default=1, verbose_name='Estado (activo/inactivo)')),
            ],
            options={
                'verbose_name': 'MaquinaRX',
                'verbose_name_plural': 'MaquinasRX',
                'ordering': ['descripcion_maquina'],
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Codigo CIE')),
                ('coste_impresion', models.IntegerField(default=0, verbose_name='Costo impresion')),
                ('descripcion_estudio', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=1, verbose_name='Estado (activo/inactivo)')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios', to='imagenologia.clasificacionestudio')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
                'ordering': ['descripcion_estudio'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionRx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de evaluacion')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicio.especialidad')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_modificadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evalacionesRx', to='paciente.paciente', verbose_name='Paciente')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicio.sala')),
                ('servicio_auxiliar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicio.serviciosaux')),
                ('maquinarx', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='imagenologia.maquinarx')),
            ],
            options={
                'verbose_name': 'EvaluacionRx',
                'verbose_name_plural': 'EvaluacionRxs',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionRxDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impreso', models.BooleanField(default=0, verbose_name='Impreso (si/no)')),
                ('activo', models.BooleanField(default=1, verbose_name='Activo (si/no)')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imagenologia.estudio', verbose_name='Estudio')),
                ('evaluacionRx', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='imagenologia.evaluacionrx', verbose_name='Evaluacion RX')),
            ],
            options={
                'verbose_name': 'EvaluacionRxDetalle',
                'verbose_name_plural': 'EvaluacionRxDetalles',
            },
        ),
        migrations.CreateModel(
            name='PacienteExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Número de identificación')),
                ('primer_nombre', models.CharField(max_length=100, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo nombre')),
                ('primer_apellido', models.CharField(max_length=100, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo apellido')),
                ('fecha_nacimiento', models.DateField(db_index=True, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('N', 'No identificado')], default='M', max_length=1, verbose_name='Sexo')),
                ('activo', models.BooleanField(default=1, verbose_name='Activo (si/no)')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha modificado')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientesexternos_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientesexternos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente externo',
                'verbose_name_plural': 'Pacientes externos',
                'ordering': ['-fecha_creado'],
            },
        ),
        migrations.AddField(
            model_name='evaluacionrx',
            name='paciente_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='imagenologia.pacienteexterno', verbose_name='Paciente Externo'),
        ),
    ]
