# Generated by Django 5.0.11 on 2025-08-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenologia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionrx',
            name='estado',
            field=models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado'),
        ),
    ]
