# Generated by Django 5.2.4 on 2026-04-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagenologia', '0004_alter_evaluacionrx_creado_por_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacionrx',
            old_name='especialidad',
            new_name='area_atencion',
        ),
    ]
