# Generated by Django 5.2.4 on 2026-04-23 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenologia', '0005_rename_especialidad_evaluacionrx_area_atencion'),
        ('servicio', '0016_alter_unidad_clinica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionrx',
            name='unidad_clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicio.unidad_clinica'),
        ),
    ]
