# Generated by Django 5.2.4 on 2026-04-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagenologia', '0006_evaluacionrx_unidad_clinica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionrx',
            name='area_atencion',
        ),
        migrations.RemoveField(
            model_name='evaluacionrx',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='evaluacionrx',
            name='servicio_auxiliar',
        ),
    ]
