# Generated by Django 5.2.4 on 2025-11-09 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIE10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'CIE10',
                'verbose_name_plural': 'CIE10',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Condicion_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_condicion_paciente', models.CharField(max_length=100, unique=True)),
                ('estado', models.BooleanField(default=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Condicion del paciente',
                'verbose_name_plural': 'Condiciones del paciente',
                'ordering': ['nombre_condicion_paciente'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_personal_salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_personal', models.CharField(max_length=100, unique=True)),
                ('estado', models.BooleanField(default=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de personal de salud',
                'verbose_name_plural': 'Tipos de personal de salud',
                'ordering': ['nombre_tipo_personal'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_diagnostico', models.CharField(max_length=200, unique=True)),
                ('estado', models.BooleanField(default=1, verbose_name='Estado')),
                ('cie10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinico.cie10')),
            ],
            options={
                'verbose_name': 'Diagnostico',
                'verbose_name_plural': 'Diagnosticos',
                'ordering': ['nombre_diagnostico'],
            },
        ),
    ]
