# Generated by Django 5.2.4 on 2026-04-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la especialidad')),
                ('nombre_corto_especialidad', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Nombre corto')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre_especialidad'],
            },
        ),
    ]
