# Generated by Django 5.2.4 on 2026-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0002_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_atencion', models.CharField(max_length=100, unique=True)),
                ('prioridad', models.PositiveSmallIntegerField(choices=[(1, 'ORDINARIA'), (2, 'PREFERENTE')], db_index=True, default=1)),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
            ],
            options={
                'verbose_name': 'Tipo de atencion',
                'verbose_name_plural': 'Tipos de atencion',
                'ordering': ['nombre_tipo_atencion'],
            },
        ),
    ]
