# Generated by Django 5.2.4 on 2026-05-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0003_tipo_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_atencion',
            name='nombre_corto_tipo_atencion',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Nombre corto'),
        ),
    ]
