# Generated by Django 5.2.4 on 2026-08-14 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinico', '0004_tipo_atencion_nombre_corto_tipo_atencion'),
        ('expediente', '0011_remove_expedienteubicacion_expubic_clinica_xor_noclinica'),
        ('ingreso', '0005_ingreso_estado'),
        ('paciente', '0021_alter_defuncion_options_and_more'),
        ('servicio', '0018_alter_cama_estado_alter_unidad_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'db_table': 'egresos_procedimiento',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='AreaEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre del área')),
                ('tipo', models.CharField(choices=[('CENSO', 'Censo'), ('OBSERVACION', 'Observación')], default='CENSO', max_length=12)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden de despliegue')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_egreso', to='servicio.servicio', verbose_name='Servicio relacionado')),
            ],
            options={
                'verbose_name': 'Área de Egreso',
                'verbose_name_plural': 'Áreas de Egreso',
                'db_table': 'egresos_area',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='N.º (correlativo del día en el registro de Estadística)')),
                ('pagina', models.CharField(blank=True, max_length=20, null=True, verbose_name='Página del libro de Estadística (manual)')),
                ('fecha_egreso', models.DateField(verbose_name='Fecha de egreso')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('edad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('procedencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Procedencia (áreas de observación)')),
                ('sexo', models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, null=True)),
                ('condicion', models.CharField(blank=True, choices=[('V', 'Vivo'), ('M', 'Muerto')], max_length=1, null=True, verbose_name='Condición al egreso (Vivo/Muerto)')),
                ('peso_gramos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso (gramos)')),
                ('tipo_referencia', models.CharField(blank=True, choices=[('TRAE', 'Trae referencia'), ('REFERIDO', 'Referido a')], max_length=10, null=True)),
                ('referencia_texto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Institución de la referencia')),
                ('epicrisis', models.BooleanField(blank=True, null=True, verbose_name='¿Tiene epicrisis? (Sí/No)')),
                ('deberia_ir_sala', models.BooleanField(blank=True, null=True, verbose_name='¿Debería ir a sala? (Sí/No)')),
                ('en_censo', models.BooleanField(default=False, verbose_name='Incluido en el censo')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to='egresos.areaegreso', verbose_name='Área del censo (elegida al digitar)')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egresos_creados', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos', to='expediente.expediente', verbose_name='Expediente')),
                ('ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos', to='ingreso.ingreso', verbose_name='Ingreso de origen')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egresos_modificados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to='paciente.paciente', verbose_name='Paciente')),
                ('operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos', to='egresos.procedimiento', verbose_name='Operación (procedimiento)')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'db_table': 'egresos_egreso',
                'ordering': ['-fecha_egreso', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='EgresoDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Diagnóstico de ingreso'), ('EGRESO', 'Diagnóstico de egreso')], default='EGRESO', max_length=8)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('cie10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egreso_diagnosticos', to='clinico.cie10', verbose_name='Código CIE10')),
                ('egreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='egresos.egreso')),
            ],
            options={
                'verbose_name': 'Diagnóstico de Egreso',
                'verbose_name_plural': 'Diagnósticos de Egreso',
                'db_table': 'egresos_diagnostico',
                'ordering': ['egreso', 'tipo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='LoteEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('fecha_captura_estadistica', models.DateTimeField(auto_now_add=True)),
                ('fecha_captura_admision', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario_admision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_egreso_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Recibió (Admisión)')),
                ('usuario_estadistica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_egreso_capturados', to=settings.AUTH_USER_MODEL, verbose_name='Capturó (Estadística)')),
            ],
            options={
                'verbose_name': 'Lote de Egresos',
                'verbose_name_plural': 'Lotes de Egresos',
                'db_table': 'egresos_lote',
                'ordering': ['-fecha_captura_estadistica'],
            },
        ),
        migrations.CreateModel(
            name='LoteEgresoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PRESTADO', 'Prestado a Estadística'), ('DEVUELTO', 'Devuelto')], default='PRESTADO', max_length=10)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_egreso_detalle', to='expediente.expediente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='egresos.loteegreso')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_egreso_detalle', to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'Detalle de Lote de Egresos',
                'verbose_name_plural': 'Detalles de Lote de Egresos',
                'db_table': 'egresos_lote_detalle',
                'unique_together': {('lote', 'expediente')},
            },
        ),
    ]
