# Generated by Django 5.2.4 on 2026-08-14 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0002_seed_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='lote_detalle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egreso', to='egresos.loteegresodetalle', verbose_name='Detalle de lote de origen'),
        ),
    ]
