# Generated by Django 5.2.4 on 2026-08-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0003_egreso_lote_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteegreso',
            name='fecha_envio_admision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loteegreso',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_REVISION', 'En revisión (Admisión)'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=12),
        ),
    ]
