# Generated by Django 5.2.4 on 2026-08-17 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0004_loteegreso_fecha_envio_admision_and_more'),
        ('servicio', '0018_alter_cama_estado_alter_unidad_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='autopsia',
            field=models.BooleanField(default=False, verbose_name='¿Autopsia?'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='causa_accidente',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Causa de accidente o violencia'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='condicion_egreso_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Condición de egreso (número)'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='egreso_sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_por_sala', to='servicio.sala', verbose_name='Egreso de (sala)'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='egreso_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_por_servicio', to='servicio.servicio', verbose_name='Egreso de (servicio)'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='hora_egreso',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de egreso'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='lugar_accidente',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Lugar de accidente o violencia'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='numero_embarazo',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de embarazo (incluyendo este)'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='parto_o_aborto',
            field=models.CharField(blank=True, choices=[('PARTO', 'Parto'), ('ABORTO', 'Aborto')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='egreso',
            name='periodo_gestacional_semanas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Período gestacional (semanas)'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='personal_atendio_parto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Personal que atendió el parto'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='razon_egreso_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Razón de egreso (número)'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='referido_institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_referidos', to='servicio.institucion_salud', verbose_name='Referido a (institución)'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='total_consultas_prenatales',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total de consultas prenatales'),
        ),
        migrations.CreateModel(
            name='ProcedimientoQuirurgico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('dia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('egreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_quirurgicos', to='egresos.egreso')),
            ],
            options={
                'verbose_name': 'Procedimiento Quirúrgico',
                'verbose_name_plural': 'Procedimientos Quirúrgicos',
                'db_table': 'egresos_proc_quirurgico',
                'ordering': ['egreso', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ProductoEmbarazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(default=1)),
                ('sexo', models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, null=True)),
                ('condicion', models.CharField(blank=True, choices=[('V', 'Vivo'), ('M', 'Muerto')], max_length=1, null=True)),
                ('peso_gramos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso al nacer (gramos)')),
                ('egreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_embarazo', to='egresos.egreso')),
            ],
            options={
                'verbose_name': 'Producto del Embarazo',
                'verbose_name_plural': 'Productos del Embarazo',
                'db_table': 'egresos_producto_embarazo',
                'ordering': ['egreso', 'numero'],
            },
        ),
    ]
