# Generated by Django 5.2.4 on 2026-08-18 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0005_egreso_autopsia_egreso_causa_accidente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to='egresos.areaegreso', verbose_name='Área del censo (se define en el reporte)'),
        ),
    ]
