# Generated by Django 5.0.11 on 2025-03-12 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0001_initial'),
        ('ubicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion_diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_clasificacion', models.CharField(max_length=50, unique=True, verbose_name='Tipos')),
                ('estado', models.BooleanField(default=1, verbose_name='Estado (activo/inactivo)')),
            ],
            options={
                'verbose_name': 'Clasificacion_diagnostico',
                'verbose_name_plural': 'Clasificaciones',
                'ordering': ['descripcion_clasificacion'],
            },
        ),
        migrations.CreateModel(
            name='Estado_civil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_estado_civil', models.CharField(max_length=50, unique=True, verbose_name='Estado Civil')),
                ('estado', models.BooleanField(default=1, verbose_name='Estado (activo/inactivo)')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civiles',
                'ordering': ['descripcion_estado_civil'],
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_nacionalidad', models.CharField(max_length=100, unique=True, verbose_name='Nacionalidad')),
                ('descripcion_corta', models.CharField(blank=True, max_length=5, null=True)),
                ('estado', models.BooleanField(default=1, verbose_name='Estado (activo/inactivo)')),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
                'ordering': ['descripcion_nacionalidad'],
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_ocupacion', models.CharField(max_length=50, unique=True, verbose_name='Ocupacion')),
                ('estado', models.BooleanField(default=1, verbose_name='Estado (activo/inactivo)')),
            ],
            options={
                'verbose_name': 'Ocupacion',
                'verbose_name_plural': 'Ocupaciones',
                'ordering': ['descripcion_ocupacion'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tipo', models.CharField(max_length=50, unique=True, verbose_name='Tipos')),
                ('descripcion_corta', models.CharField(blank=True, max_length=5, null=True)),
                ('estado', models.BooleanField(default=1, verbose_name='Estado (activo/inactivo)')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['descripcion_tipo'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numero de identificacion')),
                ('primer_nombre', models.CharField(max_length=100, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo nombre')),
                ('primer_apellido', models.CharField(max_length=100, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefono')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('P', 'Pasivo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado')),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('N', 'No identificado')], default='M', max_length=1, verbose_name='Sexo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('clasificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente_clasificacion', to='paciente.clasificacion_diagnostico', verbose_name='Clasificacion paciente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_creados', to=settings.AUTH_USER_MODEL)),
                ('estado_civil', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='paciente.estado_civil')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_modificados', to=settings.AUTH_USER_MODEL)),
                ('nacionalidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='paciente.nacionalidad', verbose_name='Nacionalidad')),
                ('ocupacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='paciente.ocupacion')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.sector', verbose_name='Domicilio')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.zona', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['fecha_modificado', 'primer_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numero de identificacion')),
                ('nombre1', models.CharField(blank=True, max_length=100, null=True, verbose_name='primer nombre')),
                ('nombre2', models.CharField(blank=True, max_length=100, null=True, verbose_name='segundo nombre')),
                ('apellido1', models.CharField(blank=True, max_length=100, null=True, verbose_name='primer apelllido')),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True, verbose_name='segundo apelllido')),
                ('tipo', models.CharField(choices=[('01', 'Padre'), ('02', 'Madre')], default='02', max_length=2, verbose_name='Parentezco')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ubicacion.sector', verbose_name='Domicilio')),
                ('paciente_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Paciente_ref', to='paciente.paciente', verbose_name='paciente_ref')),
            ],
            options={
                'verbose_name': 'Madre/Padre',
                'verbose_name_plural': 'Madre/Padre',
                'ordering': ['fecha_modificado', 'nombre1', 'nombre2'],
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_madre', to='paciente.padre', verbose_name='Madre'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_padre', to='paciente.padre', verbose_name='Padre'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='paciente_tipos', to='paciente.tipo', verbose_name='Tipo Identificacion paciente'),
        ),
    ]
