# Generated by Django 5.0.11 on 2025-03-13 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='paciente.estado_civil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacion',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='paciente.ocupacion'),
        ),
        migrations.AlterField(
            model_name='padre',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ubicacion.sector', verbose_name='Direccion'),
        ),
    ]
