# Generated by Django 5.0.11 on 2025-04-11 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_paciente_estado_civil_alter_paciente_ocupacion_and_more'),
        ('servicio', '0005_alter_servicio_nombre_corto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defuncion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_defuncion', models.DateField(verbose_name='Fecha de defunción')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo del fallecimiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defuncion', to='paciente.paciente')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sala', to='servicio.sala')),
            ],
            options={
                'verbose_name': 'Defuncion',
                'verbose_name_plural': 'Defunciones',
                'ordering': ['fecha_defuncion', 'sala'],
            },
        ),
    ]
