# Generated by Django 5.0.11 on 2025-04-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_defuncion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_sai',
            field=models.DateField(blank=True, null=True, verbose_name='FechaSAI'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sai',
            field=models.BooleanField(default=False, verbose_name='PacienteSAI'),
        ),
    ]
