# Generated by Django 5.0.11 on 2025-05-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_paciente_fecha_sai_paciente_sai'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='orden_gemelar',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Numero de gestacion'),
        ),
    ]
