# Generated by Django 5.0.11 on 2025-05-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_paciente_orden_gemelar'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuncion',
            name='DNIreponsable',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='repoonsable cadaver'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='reponsable',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='repoonsable cadaver'),
        ),
    ]
