# Generated by Django 5.0.11 on 2025-05-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_defuncion_dnireponsable_defuncion_reponsable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defuncion',
            old_name='DNIreponsable',
            new_name='reponsable_dni',
        ),
        migrations.RemoveField(
            model_name='defuncion',
            name='reponsable',
        ),
        migrations.AddField(
            model_name='defuncion',
            name='reponsable_nombre',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='reponsable cadaver'),
        ),
    ]
