# Generated by Django 5.0.1 on 2025-06-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_rename_dnireponsable_defuncion_reponsable_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Numero de identificacion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('P', 'Pasivo'), ('I', 'Inactivo')], db_index=True, default='A', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='padre',
            name='dni',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Numero de identificacion'),
        ),
    ]
