# Generated by Django 5.0.1 on 2025-06-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_alter_paciente_dni_alter_paciente_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='expediente_numero',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sai',
            field=models.BooleanField(db_index=True, default=False, verbose_name='PacienteSAI'),
        ),
    ]
