# Generated by Django 5.0.11 on 2025-06-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_paciente_expediente_numero_alter_paciente_sai'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='adolescente',
            field=models.BooleanField(db_index=True, default=False, verbose_name='PacienteAdolescente'),
        ),
    ]
