# Generated by Django 5.0.1 on 2025-06-19 03:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0010_paciente_adolescente'),
        ('servicio', '0006_especialidad'),
        ('ubicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(db_index=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['estado', 'sai', 'adolescente'], name='idx_estado_sai_adol'),
        ),
    ]
