# Generated by Django 5.0.11 on 2025-08-16 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0011_alter_paciente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padre',
            name='paciente_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Paciente_ref', to='paciente.paciente', verbose_name='paciente_ref'),
        ),
    ]
