# Generated by Django 5.2.4 on 2026-02-17 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_alter_padre_paciente_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Codigo Etnia')),
                ('descripcion_etnia', models.CharField(max_length=100, unique=True, verbose_name='Etnia')),
                ('estado', models.BooleanField(default=1, verbose_name='Estado (activo/inactivo)')),
            ],
            options={
                'verbose_name': 'Etnia',
                'verbose_name_plural': 'Etnias',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='etnia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='paciente.etnia', verbose_name='Etnia'),
        ),
    ]
