# Generated by Django 5.2.4 on 2026-03-23 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0013_etnia_paciente_etnia'),
        ('servicio', '0010_alter_institucion_salud_codigo_sesal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObitoFetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obito', models.DateField(verbose_name='Fecha de óbito fetal')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo')),
                ('responsable_dni', models.CharField(blank=True, max_length=40, null=True, verbose_name='DNI responsable')),
                ('responsable_nombre', models.CharField(blank=True, max_length=40, null=True, verbose_name='Responsable')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('estado', models.BooleanField(default=1, verbose_name='Estado (activo/inactivo)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obitos_fetales', to='paciente.paciente', verbose_name='Paciente (madre)')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obitos_fetales_sala', to='servicio.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Obito Fetal',
                'verbose_name_plural': 'Obitos Fetales',
                'ordering': ['-fecha_obito'],
            },
        ),
    ]
