# Generated by Django 5.2.4 on 2026-03-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0014_obitofetal'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuncion',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega de cadaver'),
        ),
        migrations.AlterField(
            model_name='defuncion',
            name='reponsable_dni',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='reponsable cadaver'),
        ),
    ]
