# Generated by Django 5.2.4 on 2026-03-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0015_defuncion_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuncion',
            name='tipo_defuncion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hospitalaria'), (2, 'Extrahospitalaria')], default=1),
        ),
    ]
