# Generated by Django 5.2.4 on 2026-03-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0016_defuncion_tipo_defuncion'),
    ]

    operations = [
        migrations.AddField(
            model_name='obitofetal',
            name='tipo_defuncion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Intrahospitalaria'), (2, 'Extrahospitalaria')], default=1),
        ),
        migrations.AlterField(
            model_name='defuncion',
            name='tipo_defuncion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Intrahospitalaria'), (2, 'Extrahospitalaria')], default=1),
        ),
    ]
