# Generated by Django 5.2.4 on 2026-04-01 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0017_obitofetal_tipo_defuncion_and_more'),
        ('servicio', '0010_alter_institucion_salud_codigo_sesal'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuncion',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicio.especialidad'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='servicio_auxiliar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicio.serviciosaux'),
        ),
        migrations.AddField(
            model_name='obitofetal',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicio.especialidad'),
        ),
        migrations.AddField(
            model_name='obitofetal',
            name='servicio_auxiliar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicio.serviciosaux'),
        ),
    ]
