# Generated by Django 5.2.4 on 2026-04-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0018_defuncion_especialidad_defuncion_servicio_auxiliar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defuncion',
            old_name='especialidad',
            new_name='area_atencion',
        ),
        migrations.RenameField(
            model_name='obitofetal',
            old_name='especialidad',
            new_name='area_atencion',
        ),
    ]
