# Generated by Django 5.2.4 on 2026-04-22 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0019_rename_especialidad_defuncion_area_atencion_and_more'),
        ('servicio', '0016_alter_unidad_clinica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuncion',
            name='unidad_clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicio.unidad_clinica'),
        ),
        migrations.AddField(
            model_name='obitofetal',
            name='unidad_clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicio.unidad_clinica'),
        ),
    ]
