# Generated by Django 5.2.4 on 2026-04-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0020_defuncion_unidad_clinica_obitofetal_unidad_clinica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defuncion',
            options={'ordering': ['fecha_defuncion'], 'verbose_name': 'Defuncion', 'verbose_name_plural': 'Defunciones'},
        ),
        migrations.RemoveField(
            model_name='defuncion',
            name='area_atencion',
        ),
        migrations.RemoveField(
            model_name='defuncion',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='defuncion',
            name='servicio_auxiliar',
        ),
        migrations.RemoveField(
            model_name='obitofetal',
            name='area_atencion',
        ),
        migrations.RemoveField(
            model_name='obitofetal',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='obitofetal',
            name='servicio_auxiliar',
        ),
    ]
