# Generated by Django 5.2.4 on 2025-11-09 02:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinico', '0001_initial'),
        ('paciente', '0012_alter_padre_paciente_ref'),
        ('servicio', '0009_gestor_nivel_complejidad_institucional_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo_envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_motivo_envio', models.CharField(max_length=100, unique=True)),
                ('estado', models.BooleanField(default=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Motivo de envio',
                'verbose_name_plural': 'Motivos de envio',
                'ordering': ['nombre_motivo_envio'],
            },
        ),
        migrations.CreateModel(
            name='Referencia_especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_referencia_especialidad', models.CharField(max_length=100, unique=True, verbose_name='nombre referencia especialidad')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Referencia especialidad',
                'verbose_name_plural': 'Especialidades de referencia',
                'ordering': ['nombre_referencia_especialidad'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta_Area_Capta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=100, unique=True, verbose_name='Área que capta')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Área que capta',
                'verbose_name_plural': 'Áreas que captan',
                'ordering': ['nombre_area'],
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_elaboracion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de elaboracion')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de recepcion')),
                ('tipo', models.SmallIntegerField(choices=[(0, 'Recibida'), (1, 'Enviada')], default=0, verbose_name='Tipo')),
                ('motivo_detalle', models.TextField(blank=True, null=True, verbose_name='Detalle del envio')),
                ('atencion_requerida', models.SmallIntegerField(blank=True, choices=[(1, 'EMERGENCIA OBSTETRICA'), (2, 'EMERGENCIA GENERAL'), (3, 'CONSULTA EXTERNA'), (4, 'HOSPITALIZACION'), (5, 'OTROS')], null=True, verbose_name='Atencion requerida')),
                ('oportuna', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (3, 'N/C')], null=True, verbose_name='Oportuna')),
                ('justificada', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (3, 'N/C')], null=True, verbose_name='Justificada')),
                ('motivo_no_atencion', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Fuga'), (2, 'Alta exigida'), (3, 'Otros')], null=True, verbose_name='Motivo de no atención')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estado', models.BooleanField(default=1, verbose_name='Estado')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha Editado')),
                ('area_refiere_especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referencias_enviadas_especialidad', to='servicio.especialidad')),
                ('area_refiere_sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referencias_enviadas_sala', to='servicio.sala')),
                ('area_refiere_servicio_auxiliar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referencias_enviadas_servicio_auxiliar', to='servicio.serviciosaux')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('elaborada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referencias_elaboradas', to='clinico.tipo_personal_salud')),
                ('institucion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referencias_recibidas', to='servicio.institucion_salud')),
                ('institucion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referencias_enviadas', to='servicio.institucion_salud')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_modificadas', to=settings.AUTH_USER_MODEL)),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referencias', to='referencia.motivo_envio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias', to='paciente.paciente')),
                ('especialidad_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referencias_destino', to='referencia.referencia_especialidad', verbose_name='Especialidad a la que se refiere')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
                'ordering': ['paciente__primer_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_elaboracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de elaboracion')),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de atencion')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de recepcion')),
                ('fecha_cita', models.DateField(blank=True, null=True, verbose_name='Fecha cita seguimiento')),
                ('motivo_detalle', models.TextField(blank=True, null=True, verbose_name='Detalle del envio')),
                ('atencion_requerida', models.SmallIntegerField(blank=True, choices=[(1, 'EMERGENCIA OBSTETRICA'), (2, 'EMERGENCIA GENERAL'), (3, 'CONSULTA EXTERNA'), (4, 'HOSPITALIZACION'), (5, 'OTROS')], null=True, verbose_name='Atencion requerida')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha Editado')),
                ('area_reponde_especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_reponde_especialidad', to='servicio.especialidad')),
                ('area_reponde_sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_reponde_sala', to='servicio.sala')),
                ('area_reponde_servicio_auxiliar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_reponde_servicio_auxiliar', to='servicio.serviciosaux')),
                ('area_seguimiento_especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_seguimiento_especialidad', to='servicio.especialidad')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_creadas', to=settings.AUTH_USER_MODEL)),
                ('elaborada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_elaboradas', to='clinico.tipo_personal_salud')),
                ('institucion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_enviadas_seguimiento', to='servicio.institucion_salud')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_modificadas', to=settings.AUTH_USER_MODEL)),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='referencia.motivo_envio')),
                ('referencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='referencia.referencia')),
                ('seguimiento_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_que_derivan_en_referencia', to='referencia.referencia', verbose_name='Referencia generada por el seguimiento')),
                ('area_capta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referencias_recibidas_area', to='referencia.respuesta_area_capta', verbose_name='Are que capta la referencia')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['referencia__paciente__primer_nombre'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoTic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_comunicacion', models.PositiveSmallIntegerField(choices=[(1, 'LLAMADA TELEFONICA'), (2, 'WHATSAPP'), (3, 'VISITA DOMICILIARIA'), (4, 'CORREO ELECTRONICO'), (5, 'OTRO METODO')], verbose_name='Metodo de comunicacion')),
                ('establece_comunicacion', models.BooleanField(default=False, help_text='Indica si se logró establecer comunicación con el paciente', verbose_name='Establece Comunicacion')),
                ('asistio_referencia', models.BooleanField(blank=True, default=False, null=True)),
                ('fuente_info', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'PACIENTE'), (2, 'FAMILIAR'), (3, 'AMIGO'), (4, 'PROFESIONAL DE SALUD'), (5, 'OTRO FUENTE')], null=True, verbose_name='Fuente de información')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('condicion_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.condicion_paciente', verbose_name='Condicion del paciente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('referencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento_tic', to='referencia.referencia')),
            ],
            options={
                'verbose_name': 'Seguimiento TIC',
                'verbose_name_plural': 'Seguimientos TIC',
            },
        ),
        migrations.CreateModel(
            name='Referencia_diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmada', models.BooleanField(default=True, verbose_name='Confirmada')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle diagnostico')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias', to='clinico.diagnostico')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='referencia.referencia')),
            ],
            options={
                'verbose_name': 'Diagnostico de referencia',
                'verbose_name_plural': 'Diagnosticos de referencia',
                'ordering': ['referencia'],
                'unique_together': {('referencia', 'diagnostico')},
            },
        ),
        migrations.CreateModel(
            name='Respuesta_diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle diagnostico')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_respuesta', to='clinico.diagnostico')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='referencia.respuesta')),
            ],
            options={
                'verbose_name': 'Diagnostico de respuesta',
                'verbose_name_plural': 'Diagnosticos de respuesta',
                'ordering': ['respuesta'],
                'unique_together': {('respuesta', 'diagnostico')},
            },
        ),
    ]
