# Generated by Django 5.2.4 on 2026-04-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencia', '0001_initial'),
        ('servicio', '0014_alter_area_atencion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referencia',
            old_name='area_refiere_especialidad',
            new_name='area_refiere_area_atencion',
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='area_reponde_especialidad',
            new_name='area_reponde_area_atencion',
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='area_seguimiento_especialidad',
            new_name='area_seguimiento_area_atencion',
        ),
    ]
