# Generated by Django 5.2.4 on 2026-04-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencia', '0002_remove_referencia_area_refiere_especialidad_and_more'),
        ('servicio', '0014_alter_area_atencion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='area_refiere_area_atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referencias_enviadas_area_atencion', to='servicio.area_atencion'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='area_reponde_area_atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_reponde_area_atencion', to='servicio.area_atencion'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='area_seguimiento_area_atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_seguimiento_area_atencion', to='servicio.area_atencion'),
        ),
    ]
