# Generated by Django 5.2.4 on 2026-04-24 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencia', '0003_alter_referencia_area_refiere_area_atencion_and_more'),
        ('servicio', '0016_alter_unidad_clinica_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuesta_area_capta',
            options={'ordering': ['nombre_area'], 'verbose_name': 'Area que capta', 'verbose_name_plural': 'Areas que captan'},
        ),
        migrations.AddField(
            model_name='referencia',
            name='unidad_clinica_refiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referencias_enviadas', to='servicio.unidad_clinica'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='unidad_clinica_responde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_emitidas', to='servicio.unidad_clinica'),
        ),
        migrations.AlterField(
            model_name='respuesta_area_capta',
            name='nombre_area',
            field=models.CharField(max_length=100, unique=True, verbose_name='Area que capta'),
        ),
        migrations.AlterField(
            model_name='seguimientotic',
            name='fuente_info',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'PACIENTE'), (2, 'FAMILIAR'), (3, 'AMIGO'), (4, 'PROFESIONAL DE SALUD'), (5, 'OTRO')], null=True, verbose_name='Fuente de información'),
        ),
    ]
