# Generated by Django 5.2.4 on 2026-04-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referencia', '0004_alter_respuesta_area_capta_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencia',
            name='area_refiere_area_atencion',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='area_refiere_sala',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='area_refiere_servicio_auxiliar',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='area_reponde_area_atencion',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='area_reponde_sala',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='area_reponde_servicio_auxiliar',
        ),
    ]
