# Generated by Django 5.2.4 on 2026-07-31 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencia', '0005_remove_referencia_area_refiere_area_atencion_and_more'),
        ('rrhh', '0005_personalsalud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='personal_salud_refiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referencias_realizadas', to='rrhh.personalsalud', verbose_name='Personal que refiere'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='personal_salud_responde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_realizadas', to='rrhh.personalsalud', verbose_name='Personal que responde'),
        ),
    ]
