# Generated by Django 5.2.4 on 2026-08-05 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencia', '0005_remove_referencia_area_refiere_area_atencion_and_more'),
        ('rrhh', '0005_personalsalud_estado'),
        ('servicio', '0018_alter_cama_estado_alter_unidad_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='personal_salud_refiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referencias_realizadas', to='rrhh.personalsalud', verbose_name='Personal que refiere'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='unidad_clinica_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referencias_recibidas_responsables', to='servicio.unidad_clinica'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='personal_salud_responde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_realizadas', to='rrhh.personalsalud', verbose_name='Personal de salud que responde'),
        ),
        migrations.CreateModel(
            name='ControlCalidadReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato_correcto', models.BooleanField(default=False)),
                ('letra_legible', models.BooleanField(default=False)),
                ('datos_completos', models.BooleanField(default=False)),
                ('manchones_borrones', models.BooleanField(default=False)),
                ('firma_sello', models.BooleanField(default=False)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_calidad_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_calidad_modificados', to=settings.AUTH_USER_MODEL)),
                ('referencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control_calidad', to='referencia.referencia')),
            ],
            options={
                'verbose_name': 'Control de calidad',
                'verbose_name_plural': 'Controles de calidad',
                'db_table': 'referencia_referencia_control_calidad',
            },
        ),
        migrations.CreateModel(
            name='ControlCalidadRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato_correcto', models.BooleanField(default=False)),
                ('letra_legible', models.BooleanField(default=False)),
                ('datos_completos', models.BooleanField(default=False)),
                ('manchones_borrones', models.BooleanField(default=False)),
                ('firma_sello', models.BooleanField(default=False)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_calidad_respuesta_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_calidad_respuesta_modificados', to=settings.AUTH_USER_MODEL)),
                ('respuesta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control_calidad', to='referencia.respuesta')),
            ],
            options={
                'verbose_name': 'Control de calidad de respuesta',
                'verbose_name_plural': 'Controles de calidad de respuesta',
                'db_table': 'referencia_respuesta_control_calidad',
            },
        ),
    ]
