# Generated by Django 5.2.4 on 2026-08-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencia', '0006_referencia_personal_salud_refiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='formato_sinar',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
