# Generated by Django 5.2.4 on 2026-08-21 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda_medica', '0004_configuracion_cupo_orden'),
        ('paciente', '0021_alter_defuncion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificado')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_modificadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_creado'],
            },
        ),
        migrations.CreateModel(
            name='Historial_cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.PositiveSmallIntegerField(choices=[(1, 'ASIGNACION'), (2, 'CANCELACION CUPO'), (3, 'REPROGRAMACION'), (4, 'CANCELACION CITA')])),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('actual', models.BooleanField(default=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='cita.cita')),
                ('cupo_agenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_citas', to='agenda_medica.cupo_agenda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_citas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de cita',
                'verbose_name_plural': 'Historial de citas',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente'], name='cita_cita_pacient_a1f78c_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_creado'], name='cita_cita_fecha_c_c29fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='historial_cita',
            index=models.Index(fields=['cupo_agenda'], name='cita_histor_cupo_ag_2a8dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='historial_cita',
            index=models.Index(fields=['cita'], name='cita_histor_cita_id_44744f_idx'),
        ),
        migrations.AddIndex(
            model_name='historial_cita',
            index=models.Index(fields=['cita', 'actual'], name='cita_histor_cita_id_262b24_idx'),
        ),
        migrations.AddIndex(
            model_name='historial_cita',
            index=models.Index(fields=['cita', 'fecha_movimiento'], name='cita_histor_cita_id_be7580_idx'),
        ),
        migrations.AddConstraint(
            model_name='historial_cita',
            constraint=models.UniqueConstraint(condition=models.Q(('actual', True)), fields=('cita',), name='una_relacion_actual_por_cita'),
        ),
    ]
