from .choices_constants import DetalleMapeoTipoAccion
from .view_constants import (
	ACCIONES_MAPEO_PERMITIDAS_ROL_RESTRINGIDO,
	ACCIONES_MAPEO_VALIDAS,
	ESTADOS_CON_HISTORIAL_ALTA_VACIA,
	ESTADOS_EDICION_DIRECTA_ROL_RESTRINGIDO,
	ESTADOS_MANTIENEN_INGRESO_SIN_NUEVO,
	ESTADOS_OCUPADA_PREALTA,
)


