"""Constantes usadas por vistas de mapeo_camas."""

# 2026-06-09: centraliza catálogos inline de acciones/estados para reducir acoplamiento en vistas.
ACCIONES_MAPEO_VALIDAS = (
    "CONFIRMAR",
    "CONFIRMAR_ALTA",
    "CANCELAR_PREALTA",
    "CAMBIO_TRASLADO",
    "ASIGNACION",
    "ALTA_FORZADA",
)

ACCIONES_MAPEO_PERMITIDAS_ROL_RESTRINGIDO = (
    "CONFIRMAR",
    "CAMBIO_TRASLADO",
    "CONFIRMAR_ALTA",
    "ALTA_FORZADA",
)

ESTADOS_OCUPADA_PREALTA = ("OCUPADA", "PRE_ALTA")
ESTADOS_EDICION_DIRECTA_ROL_RESTRINGIDO = ("PRE_ALTA", "VACIA")
ESTADOS_CON_HISTORIAL_ALTA_VACIA = ("OCUPADA", "PRE_ALTA", "ALTA")
ESTADOS_MANTIENEN_INGRESO_SIN_NUEVO = ("PRE_ALTA", "ALTA")
