# -----------------------------
# SP PARA REFERENCIAS
# -----------------------------
SP_CATALOGO_REFERENCIAS_RECIBIDAS = "SP_CATALOGO_REFERENCIAS_RECIBIDAS"
SP_CATALOGO_REFERENCIAS_ENVIADAS = "SP_CATALOGO_REFERENCIAS_ENVIADAS"

# -----------------------------
# SP PARA PACIENTES
# -----------------------------
SP_SIWI_PACIENTE_INSERTAR_ACTUALIZAR = "SP_SIWI_PACIENTE_INSERTAR_ACTUALIZAR"
SP_OBTENER_DISPENSACIONES_PACIENTE = "SP_OBTENER_DISPENSACIONES_PACIENTE"

# -----------------------------
# SQL SERVER (PYODBC)
# -----------------------------
SP_PACIENTE_SQLSERVER_SYNC = "PC_SIWI_PACIENTE_AGREGAR_ACTUALIZAR"
