# Generated by Django 5.0.11 on 2025-03-12 15:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_localizacion', models.CharField(max_length=100, unique=True, verbose_name='Localizacion')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Localizacion',
                'verbose_name_plural': 'Localizaciones',
                'ordering': ['descripcion_localizacion'],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número de expediente único (máximo 199999)', validators=[django.core.validators.MaxValueValidator(199999)], verbose_name='Número de expediente')),
                ('estado', models.IntegerField(choices=[(1, 'Asignado'), (2, 'Libre')], default=2, verbose_name='Estado')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_modificados', to=settings.AUTH_USER_MODEL)),
                ('localizacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='expediente.localizacion')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='PacienteAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'Actual'), ('0', 'Historico')], default='1', max_length=10)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedienteAsignados', to='expediente.expediente')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pacienteasignacion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', '1')), fields=('paciente',), name='unique_actual_paciente_expediente'),
        ),
    ]
