# Generated by Django 5.0.11 on 2025-03-13 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='numero',
            field=models.PositiveIntegerField(help_text='Número de expediente único (máximo 199999)', unique=True, validators=[django.core.validators.MaxValueValidator(199999)], verbose_name='Número de expediente'),
        ),
    ]
