# Generated by Django 5.0.11 on 2025-03-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_alter_expediente_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteasignacion',
            name='fecha_liberacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
