# Generated by Django 5.0.11 on 2025-03-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0003_pacienteasignacion_fecha_liberacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteasignacion',
            name='fecha_asignacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
