# Generated by Django 5.0.11 on 2025-08-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0004_alter_pacienteasignacion_fecha_asignacion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pacienteasignacion',
            name='unique_actual_paciente_expediente',
        ),
    ]
