# Generated by Django 5.2.4 on 2026-05-29 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0005_remove_pacienteasignacion_unique_actual_paciente_expediente'),
        ('servicio', '0016_alter_unidad_clinica_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.SmallIntegerField(choices=[(1, 'Clínica'), (2, 'No Clínica')], help_text='1=Clínica (usa unidad_clinica), 2=No Clínica (usa unidad_no_clinica)', verbose_name='Tipo de Ubicación')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('unidad_clinica', models.ForeignKey(blank=True, help_text='FK a servicio_unidad_clinica. Solo si tipo=1 (Clínica).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_expediente', to='servicio.unidad_clinica', verbose_name='Unidad Clínica')),
                ('unidad_no_clinica', models.ForeignKey(blank=True, help_text='FK a servicio_unidad. Solo si tipo=2 (No Clínica).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_expediente', to='servicio.unidad', verbose_name='Unidad No Clínica')),
            ],
            options={
                'verbose_name': 'Ubicación de Expediente',
                'verbose_name_plural': 'Ubicaciones de Expediente',
                'db_table': 'expediente_ubicacion',
                'ordering': ['tipo', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('tipo', 1), ('unidad_clinica__isnull', False), ('unidad_no_clinica__isnull', True)), models.Q(('tipo', 2), ('unidad_clinica__isnull', True), ('unidad_no_clinica__isnull', False)), _connector='OR'), name='expubic_clinica_xor_noclinica'), models.UniqueConstraint(condition=models.Q(('unidad_clinica__isnull', False)), fields=('unidad_clinica',), name='expubic_unidad_clinica_unica'), models.UniqueConstraint(condition=models.Q(('unidad_no_clinica__isnull', False)), fields=('unidad_no_clinica',), name='expubic_unidad_noclinica_unica')],
            },
        ),
    ]
