# Generated by Django 5.2.4 on 2026-05-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0006_add_expediente_ubicacion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expedienteubicacion',
            name='expubic_unidad_clinica_unica',
        ),
        migrations.RemoveConstraint(
            model_name='expedienteubicacion',
            name='expubic_unidad_noclinica_unica',
        ),
    ]
