# Generated by Django 5.2.4 on 2026-06-05 21:06

import django.db.models.deletion
from django.db import migrations, models


def _backfill_ubicacion_admision(apps, schema_editor):

    Expediente = apps.get_model("expediente", "Expediente")
    ExpedienteUbicacion = apps.get_model("expediente", "ExpedienteUbicacion")
    Unidad = apps.get_model("servicio", "Unidad")

    TIPO_NO_CLINICA = 2

    # ----------------------------
    # ADMISION
    # ----------------------------

    admision = (
        Unidad.objects.filter(nombre_unidad__iexact="ADMISION").first()
        or Unidad.objects.filter(nombre_unidad__icontains="ADMIS").first()
    )

    if admision:

        ubicacion_admision, _ = ExpedienteUbicacion.objects.get_or_create(
            unidad_no_clinica=admision,
            defaults={
                "tipo": TIPO_NO_CLINICA,
                "estado": True,
            }
        )

        Expediente.objects.filter(
            ubicacion__isnull=True
        ).update(
            ubicacion=ubicacion_admision
        )


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0007_ajustar_constraints_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='FK a expediente_ubicacion. Se actualiza con préstamos/devoluciones.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_ubicados', to='expediente.expedienteubicacion', verbose_name='Ubicación actual (catálogo unificado)'),
        ),
        migrations.RunPython(_backfill_ubicacion_admision, _noop),
    ]
