# Generated by Django 5.2.4 on 2026-06-05 21:06

import django.db.models.deletion
from django.db import migrations, models


def _backfill_ubicacion_admision(apps, schema_editor):
    """
    Inicializa la nueva columna Expediente.ubicacion en ADMISION para todos los
    expedientes existentes (transición híbrida). Guarda el ID de la fila ADMISION
    del catálogo expediente_ubicacion, NO el texto.

    Si no existe la unidad ADMISION en servicio_unidad, deja la columna en NULL
    (el flujo de préstamos la irá poblando).
    """
    Expediente = apps.get_model('expediente', 'Expediente')
    ExpedienteUbicacion = apps.get_model('expediente', 'ExpedienteUbicacion')
    Unidad = apps.get_model('servicio', 'Unidad')

    adm = (Unidad.objects.filter(nombre_unidad__iexact='ADMISION').first()
           or Unidad.objects.filter(nombre_unidad__icontains='ADMIS').first())
    if not adm:
        return

    # TIPO_NO_CLINICA = 2 (ADMISION es unidad no clínica de servicio).
    ubic, _ = ExpedienteUbicacion.objects.get_or_create(
        unidad_no_clinica=adm, defaults={'tipo': 2})

    Expediente.objects.filter(ubicacion__isnull=True).update(ubicacion=ubic)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0007_ajustar_constraints_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='FK a expediente_ubicacion. Se actualiza con préstamos/devoluciones.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_ubicados', to='expediente.expedienteubicacion', verbose_name='Ubicación actual (catálogo unificado)'),
        ),
        migrations.RunPython(_backfill_ubicacion_admision, _noop),
    ]
