# Generated by Django 5.2.4 on 2026-07-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0009_poblar_ubicaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='localizacion',
        ),
        migrations.DeleteModel(
            name='Localizacion',
        ),
    ]
