# Generated by Django 5.2.4 on 2026-07-31 16:09
# Ajuste de historial de migraciones. 2026-08-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0011_remove_expubic_clinica_xor_noclinica'),
    ]

    operations = []
