# Generated by Django 5.2.4 on 2026-07-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0010_remove_expediente_localizacion_delete_localizacion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expedienteubicacion',
            name='expubic_clinica_xor_noclinica',
        ),
    ]
