"""
Django settings for SIWI project.

Generated by 'django-admin startproject' using Django 5.0.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path
import logging.config
from pathlib import Path

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

IMAGE_SERVER_URL = os.getenv("IMAGE_SERVER_URL")
IMAGE_SERVER_USER = os.getenv("IMAGE_SERVER_USER")
IMAGE_SERVER_PASSWORD = os.getenv("IMAGE_SERVER_PASSWORD")



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.getenv("DEBUG", "0") == "1" else False

ALLOWED_HOSTS = ['SIWIH', '127.0.0.1', '192.168.88.8', '192.168.88.28', '192.168.88.173', '100.84.35.113']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dal',
    'dal_select2',
    'core',
    'servicio',
    'ubicacion',
    'reporte',
    'paciente',
    'expediente',
    'ingreso',
    'atencion',
    'imagenologia',
    'referencia',
    'clinico',
    'usuario',
    's_exp',
    'mapeo_camas',
    'sg_transporte_hospitalario',
    'rrhh'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.LoginRequiredMiddleware',  #se requiere login para servir cualquier json o pagina
    'core.middleware.NoSessionRefreshOnPollingMiddleware',  # Polling no renueva sesión
]

ROOT_URLCONF = 'SIWI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'core.context_processors.usuario_imagen',
            ],
        },
    },
]

WSGI_APPLICATION = 'SIWI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_DEFAULT_NAME'),
        'USER': os.getenv('DB_DEFAULT_USER'),
        'PASSWORD': os.getenv('DB_DEFAULT_PASSWORD'),
        'HOST': os.getenv('DB_DEFAULT_HOST'),
        'PORT': os.getenv('DB_DEFAULT_PORT'),
    },
    'censo2025': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_CENSO_NAME'),
        'USER': os.getenv('DB_CENSO_USER'),
        'PASSWORD': os.getenv('DB_CENSO_PASSWORD'),
        'HOST': os.getenv('DB_CENSO_HOST'),
        'PORT': os.getenv('DB_CENSO_PORT'),
    },
	'salmi':{
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_SALMI_NAME'),
        'USER': os.getenv('DB_SALMI_USER'),
        'PASSWORD': os.getenv('DB_SALMI_PASSWORD'),
        'HOST': os.getenv('DB_SALMI_HOST'),
        'PORT': os.getenv('DB_SALMI_PORT'),
    },
    	'BIT_LESP': {
        'ENGINE': 'mssql',
        'NAME': os.getenv('DB_BITLESP_NAME'),
        'USER': os.getenv('DB_BITLESP_USER'),
        'PASSWORD': os.getenv('DB_BITLESP_PASSWORD'),
        'HOST': os.getenv('DB_BITLESP_HOST'),
        'PORT': os.getenv('DB_BITLESP_PORT'),                   
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 4}  # Pod�s poner 3 o 2 si quer�s a�n m�s simple
    }
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es'
TIME_ZONE = "America/Tegucigalpa"
USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'


ENVIRONMENT = os.getenv("ENVIRONMENT", "development")

if ENVIRONMENT == "development":
    STATICFILES_DIRS = [os.path.join(BASE_DIR, "core", "static")]
else:
    STATIC_ROOT = '/home/sid280/SIWI/staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#login variables
LOGIN_URL = '/login/'

LOGIN_REDIRECT_URL = '/'


# Expira la sesin al cerrar el navegador (opcional)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Cierra sesin tras 30 minutos de inactividad
SESSION_COOKIE_AGE = 1800  # 30 minutos

# Reinicia el tiempo de expiraci�n con cada solicitud activa

SESSION_SAVE_EVERY_REQUEST = True


#LOGGER
BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

def _silenciar_polling_filter(record):
    """
    Filtro para django.server: descarta las líneas de access log que
    correspondan a endpoints de polling (changes-check, alertas).
    Estos endpoints se consultan cada pocos segundos y solo generan ruido
    en la consola. No se descartan errores 4xx/5xx aunque sean polling.
    """
    msg = record.getMessage()
    # Solo silenciar respuestas exitosas (200, 304) a endpoints de polling
    rutas_polling = ['/s_exp/api/changes-check/', '/s_exp/api/alertas/']
    for ruta in rutas_polling:
        if ruta in msg:
            # No silenciar si hay error (4xx, 5xx)
            if ' 200 ' in msg or ' 304 ' in msg:
                return False  # descartar este log
    return True  # mantener todo lo demás


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "standard": {
            "format": "[{asctime}] {levelname} [{name}] [{app}] {message}",
            "style": "{",
            # Valor por defecto cuando un log no pasa 'app' via extra={'app': ...}
            "defaults": {"app": "general"},
        },
    },

    "filters": {
        "silenciar_polling": {
            "()": "django.utils.log.CallbackFilter",
            "callback": _silenciar_polling_filter,
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
            "level": "INFO",
        },

        "siwi_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "siwi_backend.log",
            "maxBytes": 1024 * 1024 * 20,  # 5MB
            "backupCount": 10,
            "formatter": "standard",
            "level": "WARNING",
        },
    },

    "loggers": {
        # Logger central del sistema. Todas las apps registran aquí vía
        # core.utils.utilidades_logging (log_info/log_warning/log_error),
        # identificándose con el campo 'app' (ej. app="s_exp"). El formato
        # incluye [{app}], así que un solo archivo centraliza todo y se puede
        # filtrar por módulo. (s_exp dejó de usar su logger dedicado.)
        "siwi": {
            "handlers": ["console", "siwi_file"],
            "level": "INFO",
            "propagate": False,
        },
        # django.server emite los logs de acceso del runserver/gunicorn.
        # Aplicamos el filtro para silenciar los polling con respuesta 200.
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "filters": ["silenciar_polling"],
            "propagate": False,
        },
    },
}

