# Generated by Django 5.2.4 on 2026-03-24 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0005_remove_pacienteasignacion_unique_actual_paciente_expediente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedientePrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado'), ('Baja', 'Baja')], default='Disponible', max_length=20, verbose_name='Estado')),
                ('ubicacion_fisica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación Física')),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prestamo_info', to='expediente.expediente', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Expediente Préstamo',
                'verbose_name_plural': 'Expedientes Préstamo',
                'ordering': ['expediente__numero'],
            },
        ),
        migrations.CreateModel(
            name='LogHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('objeto_tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Objeto')),
                ('objeto_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_s_exp', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log Histórico',
                'verbose_name_plural': 'Logs Históricos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aprobacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Aprobación')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega al Solicitante')),
                ('fecha_limite', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite de Devolución')),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución Real')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios del Admin')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Entregado', 'Entregado'), ('Vencido', 'Vencido'), ('DevolucionParcial', 'Devolución Parcial'), ('Cerrado', 'Cerrado')], default='Activo', max_length=30, verbose_name='Estado del Préstamo')),
                ('tiempo_limite_horas', models.PositiveIntegerField(default=24, help_text='Mínimo 24 horas. Configurable por préstamo.', verbose_name='Tiempo Límite (horas)')),
                ('admin_aprobador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Admin que Aprobó')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_aprobacion'],
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Devolución')),
                ('cantidad_esperada', models.PositiveIntegerField(verbose_name='Cantidad Esperada')),
                ('cantidad_recibida', models.PositiveIntegerField(verbose_name='Cantidad Recibida')),
                ('estado', models.CharField(choices=[('Completa', 'Completa'), ('Incompleta', 'Incompleta'), ('Parcial', 'Parcial')], default='Completa', max_length=20, verbose_name='Estado de Devolución')),
                ('notas_admin', models.TextField(blank=True, null=True, verbose_name='Notas del Administrador')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='s_exp.prestamo', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_devolucion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudExpedienteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_solicitudes', to='s_exp.expedienteprestamo', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud',
                'verbose_name_plural': 'Detalles de Solicitud',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('estado_flujo', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Listo', 'Listo para Retirar'), ('EnPrestamo', 'En Préstamo'), ('Devuelto', 'Devuelto'), ('DevolucionParcial', 'Devolución Parcial')], default='Pendiente', max_length=30, verbose_name='Estado del Flujo')),
                ('motivo', models.TextField(verbose_name='Motivo de la Solicitud')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('area_destino', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área de Destino')),
                ('expedientes', models.ManyToManyField(related_name='solicitudes', through='s_exp.SolicitudExpedienteDetalle', to='s_exp.expedienteprestamo', verbose_name='Expedientes Solicitados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_prestamo', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Préstamo',
                'verbose_name_plural': 'Solicitudes de Préstamo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='solicitudexpedientedetalle',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='s_exp.solicitudprestamo', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prestamo', to='s_exp.solicitudprestamo', verbose_name='Solicitud'),
        ),
        migrations.AlterUniqueTogether(
            name='solicitudexpedientedetalle',
            unique_together={('solicitud', 'expediente_prestamo')},
        ),
    ]
