# Generated by Django 5.2.4 on 2026-06-12 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0008_expediente_ubicacion'),
        ('paciente', '0021_alter_defuncion_options_and_more'),
        ('servicio', '0016_alter_unidad_clinica_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre legible del Estado')),
            ],
            options={
                'verbose_name': 'Estado de Devolución',
                'verbose_name_plural': 'Estados de Devolución',
                'db_table': 's_exp_estadodevolucion',
            },
        ),
        migrations.CreateModel(
            name='EstadoExpedienteFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Estado')),
            ],
            options={
                'verbose_name': 'Estado de Expediente Físico',
                'verbose_name_plural': 'Estados de Expediente Físico',
                'db_table': 's_exp_estadoexpedientefisico',
            },
        ),
        migrations.CreateModel(
            name='EstadoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre legible del Estado')),
            ],
            options={
                'verbose_name': 'Estado de Préstamo',
                'verbose_name_plural': 'Estados de Préstamo',
                'db_table': 's_exp_estadoprestamo',
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Estado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado de Solicitud',
                'verbose_name_plural': 'Estados de Solicitud',
                'db_table': 's_exp_estadosolicitud',
            },
        ),
        migrations.CreateModel(
            name='MotivoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Motivo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Motivo de Solicitud',
                'verbose_name_plural': 'Motivos de Solicitud',
                'db_table': 's_exp_motivosolicitud',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoAccionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre legible de la Acción')),
            ],
            options={
                'verbose_name': 'Tipo de Acción (Log)',
                'verbose_name_plural': 'Tipos de Acción (Log)',
                'db_table': 's_exp_tipoaccionlog',
            },
        ),
        migrations.CreateModel(
            name='TipoObjetoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre legible del Tipo de Objeto')),
            ],
            options={
                'verbose_name': 'Tipo de Objeto (Log)',
                'verbose_name_plural': 'Tipos de Objeto (Log)',
                'db_table': 's_exp_tipoobjetolog',
            },
        ),
        migrations.CreateModel(
            name='ExpedientePrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='s_exp.estadoexpedientefisico', verbose_name='Estado Físico Actual')),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prestamo_info', to='expediente.expediente', verbose_name='Expediente')),
                ('ubicacion', models.ForeignKey(blank=True, help_text='FK a expediente_ubicacion. Se actualiza al entregar/devolver.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_prestamo', to='expediente.expedienteubicacion', verbose_name='Ubicación actual (catálogo)')),
            ],
            options={
                'verbose_name': 'Expediente Préstamo',
                'verbose_name_plural': 'Expedientes Préstamo',
                'db_table': 's_exp_expedienteprestamo',
                'ordering': ['expediente__numero'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aprobacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Aprobación')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega al Solicitante')),
                ('fecha_limite', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite de Devolución')),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución Real')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios del Admin')),
                ('alerta_vencimiento_leida_at', models.DateTimeField(blank=True, null=True, verbose_name='Última alerta de vencimiento aceptada')),
                ('tiempo_limite_horas', models.PositiveIntegerField(default=24, help_text='Configurable por préstamo. Representa horas por defecto o minutos si es_minutos es True.', verbose_name='Tiempo Límite')),
                ('es_minutos', models.BooleanField(default=False, help_text='Solo para pruebas. Si es True, el tiempo límite se cuenta en minutos.', verbose_name='¿Es en minutos?')),
                ('admin_aprobador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Admin que Aprobó')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='s_exp.estadoprestamo', verbose_name='Estado del Préstamo')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'db_table': 's_exp_prestamo',
                'ordering': ['-fecha_aprobacion'],
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Devolución')),
                ('cantidad_esperada', models.PositiveIntegerField(verbose_name='Cantidad Esperada')),
                ('cantidad_recibida', models.PositiveIntegerField(verbose_name='Cantidad Recibida')),
                ('notas_admin', models.TextField(blank=True, null=True, verbose_name='Notas del Administrador')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='s_exp.estadodevolucion', verbose_name='Estado de Devolución')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='s_exp.prestamo', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'db_table': 's_exp_devolucion',
                'ordering': ['-fecha_devolucion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudExpedienteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=True, verbose_name='Expediente Aprobado para préstamo')),
                ('motivo_rechazo_individual', models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo del expediente')),
                ('devuelto', models.BooleanField(default=False, verbose_name='Devuelto')),
                ('fuera_de_tiempo', models.BooleanField(default=False, verbose_name='Entregado fuera de tiempo')),
                ('comentario_devolucion', models.TextField(blank=True, null=True, verbose_name='Comentario de devolución del expediente')),
                ('expediente_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_solicitudes', to='s_exp.expedienteprestamo', verbose_name='Expediente')),
                ('paciente', models.ForeignKey(blank=True, help_text='FK al paciente. Para mostrar nombre/identidad se consulta en vivo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_expediente_detalle', to='paciente.paciente', verbose_name='Paciente vinculado al momento de la solicitud')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud',
                'verbose_name_plural': 'Detalles de Solicitud',
                'db_table': 's_exp_solicituddetalle',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('notificado_listo', models.BooleanField(default=False, verbose_name='Notificado al usuario (Listo para recoger)')),
                ('tiempo_sugerido_horas', models.PositiveIntegerField(blank=True, help_text='Sugerencia opcional del usuario al crear la solicitud. Mismo día: máx hasta 4:00 PM. Días posteriores: máx 72 horas.', null=True, verbose_name='Tiempo sugerido por el solicitante (horas)')),
                ('estado_flujo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='s_exp.estadosolicitud', verbose_name='Estado de la Solicitud')),
                ('expedientes', models.ManyToManyField(related_name='solicitudes', through='s_exp.SolicitudExpedienteDetalle', to='s_exp.expedienteprestamo', verbose_name='Expedientes Solicitados')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='s_exp.motivosolicitud', verbose_name='Motivo de la Solicitud')),
                ('servicio_unidad', models.ForeignKey(blank=True, help_text='FK a servicio.Unidad. Capturada del registro RRHH al crear la solicitud.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_prestamo', to='servicio.unidad', verbose_name='Unidad de Servicio del Solicitante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_prestamo', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Préstamo',
                'verbose_name_plural': 'Solicitudes de Préstamo',
                'db_table': 's_exp_solicitudprestamo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='solicitudexpedientedetalle',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='s_exp.solicitudprestamo', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prestamo', to='s_exp.solicitudprestamo', verbose_name='Solicitud'),
        ),
        migrations.CreateModel(
            name='ExpedienteEstadoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('estado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs_como_anterior', to='s_exp.estadoexpedientefisico', verbose_name='Estado Anterior')),
                ('estado_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_como_nuevo', to='s_exp.estadoexpedientefisico', verbose_name='Estado Nuevo')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados_fisicos', to='expediente.expediente', verbose_name='Expediente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado_fisico', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que cambió')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_expediente', to='s_exp.solicitudprestamo', verbose_name='Solicitud Relacionada')),
            ],
            options={
                'verbose_name': 'Transacción de Estado',
                'verbose_name_plural': 'Transacciones de Estados',
                'db_table': 's_exp_expedienteestadolog',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LogHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('objeto_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_s_exp', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='s_exp.tipoaccionlog', verbose_name='Acción')),
                ('objeto_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='s_exp.tipoobjetolog', verbose_name='Tipo de Objeto')),
            ],
            options={
                'verbose_name': 'Log Histórico',
                'verbose_name_plural': 'Logs Históricos',
                'db_table': 's_exp_loghistorico',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='solicitudexpedientedetalle',
            unique_together={('solicitud', 'expediente_prestamo')},
        ),
    ]
