# Generated by Django 5.2.4 on 2026-03-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_exp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='devolucion',
            table='s_exp_devolucion',
        ),
        migrations.AlterModelTable(
            name='expedienteprestamo',
            table='s_exp_expedienteprestamo',
        ),
        migrations.AlterModelTable(
            name='loghistorico',
            table='s_exp_loghistorico',
        ),
        migrations.AlterModelTable(
            name='prestamo',
            table='s_exp_prestamo',
        ),
        migrations.AlterModelTable(
            name='solicitudexpedientedetalle',
            table='s_exp_solicituddetalle',
        ),
        migrations.AlterModelTable(
            name='solicitudprestamo',
            table='s_exp_solicitudprestamo',
        ),
    ]
