# Generated by Django 5.2.4 on 2026-04-13 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0005_remove_pacienteasignacion_unique_actual_paciente_expediente'),
        ('s_exp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoExpedienteFisico',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código (Ejem: EXP_DISPONIBLE)')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Estado')),
            ],
            options={
                'verbose_name': 'Estado de Expediente Físico',
                'verbose_name_plural': 'Estados de Expediente Físico',
                'db_table': 's_exp_estadoexpedientefisico',
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código (Ejem: SOL_PENDIENTE)')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Estado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado de Solicitud',
                'verbose_name_plural': 'Estados de Solicitud',
                'db_table': 's_exp_estadosolicitud',
            },
        ),
        migrations.AlterField(
            model_name='expedienteprestamo',
            name='estado',
            field=models.ForeignKey(default='EXP_DISPONIBLE', on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='s_exp.estadoexpedientefisico', verbose_name='Estado Físico Actual'),
        ),
        migrations.AlterField(
            model_name='solicitudprestamo',
            name='estado_flujo',
            field=models.ForeignKey(default='SOL_PENDIENTE', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='s_exp.estadosolicitud', verbose_name='Estado de la Solicitud'),
        ),
        migrations.CreateModel(
            name='ExpedienteEstadoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('estado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs_como_anterior', to='s_exp.estadoexpedientefisico', verbose_name='Estado Anterior')),
                ('estado_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_como_nuevo', to='s_exp.estadoexpedientefisico', verbose_name='Estado Nuevo')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados_fisicos', to='expediente.expediente', verbose_name='Expediente')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_expediente', to='s_exp.solicitudprestamo', verbose_name='Solicitud Relacionada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado_fisico', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que cambió')),
            ],
            options={
                'verbose_name': 'Transacción de Estado',
                'verbose_name_plural': 'Transacciones de Estados',
                'db_table': 's_exp_expedienteestadolog',
                'ordering': ['-fecha'],
            },
        ),
    ]
