# Generated by Django 5.2.4 on 2026-04-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_exp', '0002_estadoexpedientefisico_estadosolicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudexpedientedetalle',
            name='fuera_de_tiempo',
            field=models.BooleanField(default=False, verbose_name='Entregado fuera de tiempo'),
        ),
    ]
