# Generated by Django 5.2.4 on 2026-07-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_exp', '0002_datos_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudexpedientedetalle',
            name='comentario_usuario_devolucion',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario del usuario al iniciar la devolución'),
        ),
        migrations.AddField(
            model_name='solicitudexpedientedetalle',
            name='usuario_solicita_devolver',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='El usuario solicitó devolver este expediente'),
        ),
    ]
