# Generated by Django 5.2.4 on 2026-03-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_exp', '0002_alter_devolucion_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudexpedientedetalle',
            name='numero_expediente',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='N° Expediente (snapshot)'),
        ),
        migrations.AddField(
            model_name='solicitudexpedientedetalle',
            name='paciente_identidad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Identidad del Paciente'),
        ),
        migrations.AddField(
            model_name='solicitudexpedientedetalle',
            name='paciente_nombre',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre del Paciente'),
        ),
        migrations.AlterField(
            model_name='solicitudprestamo',
            name='estado_flujo',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Listo', 'Listo para Retirar'), ('EnPrestamo', 'En Préstamo'), ('Devuelto', 'Devuelto'), ('DevolucionParcial', 'Devolución Parcial'), ('Anulado', 'Anulado')], default='Pendiente', max_length=30, verbose_name='Estado del Flujo'),
        ),
    ]
