# Generated by Django 5.2.4 on 2026-04-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_exp', '0003_solicitudexpedientedetalle_fuera_de_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprestamo',
            name='notificado_listo',
            field=models.BooleanField(default=False, verbose_name='Notificado al usuario (Listo para recoger)'),
        ),
    ]
