# Generated by Django 5.2.4 on 2026-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_exp', '0004_estado_pendiente_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudexpedientedetalle',
            name='comentario_pendiente',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario del préstamo pendiente'),
        ),
        migrations.AddField(
            model_name='solicitudexpedientedetalle',
            name='prestamo_pendiente',
            field=models.BooleanField(default=False, verbose_name='Marcado como préstamo pendiente'),
        ),
    ]
