# Generated by Django 5.2.4 on 2026-04-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_exp', '0004_solicitudprestamo_notificado_listo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='alerta_vencimiento_leida_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última alerta de vencimiento aceptada'),
        ),
    ]
