# Generated by Django 5.2.4 on 2026-04-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_exp', '0005_prestamo_alerta_vencimiento_leida_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='es_minutos',
            field=models.BooleanField(default=False, help_text='Solo para pruebas. Si es True, el tiempo límite se cuenta en minutos.', verbose_name='¿Es en minutos?'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tiempo_limite_horas',
            field=models.PositiveIntegerField(default=24, help_text='Configurable por préstamo. Representa horas por defecto o minutos si es_minutos es True.', verbose_name='Tiempo Límite'),
        ),
    ]
