# Generated by Django 5.2.4 on 2026-07-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_exp', '0005_solicitudexpedientedetalle_comentario_pendiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudexpedientedetalle',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora en que se devolvió este expediente'),
        ),
        migrations.AddField(
            model_name='solicitudexpedientedetalle',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora en que se entregó este expediente'),
        ),
    ]
