# Generated by Django 5.2.4 on 2026-07-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_exp', '0007_backfill_fechas_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudexpedientedetalle',
            name='motivo_recuperacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo/observaciones de la recuperación de urgencia'),
        ),
        migrations.AddField(
            model_name='solicitudexpedientedetalle',
            name='recuperacion_leida',
            field=models.BooleanField(default=False, verbose_name='El usuario ya vio el aviso de la recuperación'),
        ),
        migrations.AddField(
            model_name='solicitudexpedientedetalle',
            name='recuperado_admision',
            field=models.BooleanField(default=False, verbose_name='Recuperado de urgencia por Admisión'),
        ),
    ]
