# Generated by Django 5.2.4 on 2026-05-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_exp', '0011_fix_rechazados_disponibles'),
        ('servicio', '0016_alter_unidad_clinica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprestamo',
            name='servicio_unidad',
            field=models.ForeignKey(blank=True, help_text='Obtenida automáticamente del registro en RRHH del usuario solicitante', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_prestamo', to='servicio.unidad', verbose_name='Unidad de Servicio del Solicitante'),
        ),
    ]
