# Generated by Django 5.2.4 on 2026-05-28 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0021_alter_defuncion_options_and_more'),
        ('s_exp', '0012_add_servicio_unidad_to_solicitud'),
        ('servicio', '0016_alter_unidad_clinica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudexpedientedetalle',
            name='paciente',
            field=models.ForeignKey(blank=True, help_text='FK al paciente. Para mostrar nombre/identidad se consulta en vivo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_expediente_detalle', to='paciente.paciente', verbose_name='Paciente vinculado al momento de la solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitudexpedientedetalle',
            name='numero_expediente',
            field=models.PositiveIntegerField(blank=True, help_text='Usar expediente_prestamo.expediente.numero en su lugar', null=True, verbose_name='[DEPRECATED] N° Expediente (snapshot)'),
        ),
        migrations.AlterField(
            model_name='solicitudexpedientedetalle',
            name='paciente_identidad',
            field=models.CharField(blank=True, help_text='Usar paciente.dni en su lugar via servicios', max_length=50, null=True, verbose_name='[DEPRECATED] Identidad del Paciente'),
        ),
        migrations.AlterField(
            model_name='solicitudexpedientedetalle',
            name='paciente_nombre',
            field=models.CharField(blank=True, help_text='Usar paciente.nombre_completo en su lugar via servicios', max_length=300, null=True, verbose_name='[DEPRECATED] Nombre del Paciente'),
        ),
        migrations.AlterField(
            model_name='solicitudprestamo',
            name='area_destino',
            field=models.CharField(blank=True, help_text='Usar servicio_unidad en su lugar via servicios', max_length=100, null=True, verbose_name='[DEPRECATED] Área de Destino'),
        ),
        migrations.AlterField(
            model_name='solicitudprestamo',
            name='servicio_unidad',
            field=models.ForeignKey(blank=True, help_text='FK a servicio.Unidad. Capturada del registro RRHH al crear la solicitud.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_prestamo', to='servicio.unidad', verbose_name='Unidad de Servicio del Solicitante'),
        ),
    ]
