# Generated by Django 5.2.4 on 2026-05-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_exp', '0014_backfill_paciente_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudexpedientedetalle',
            name='numero_expediente',
        ),
        migrations.RemoveField(
            model_name='solicitudexpedientedetalle',
            name='paciente_identidad',
        ),
        migrations.RemoveField(
            model_name='solicitudexpedientedetalle',
            name='paciente_nombre',
        ),
        migrations.RemoveField(
            model_name='solicitudprestamo',
            name='area_destino',
        ),
    ]
