# Generated by Django 5.2.4 on 2026-05-29 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0007_ajustar_constraints_ubicacion'),
        ('s_exp', '0015_eliminar_campos_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedienteprestamo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='FK a expediente_ubicacion. Se actualiza al entregar/devolver.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_prestamo', to='expediente.expedienteubicacion', verbose_name='Ubicación actual (catálogo)'),
        ),
        migrations.AlterField(
            model_name='expedienteprestamo',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='[DEPRECATED] Ubicación Física (texto)'),
        ),
    ]
