# Generated by Django 5.2.4 on 2026-06-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_exp', '0016_add_ubicacion_fk_expedienteprestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDevolucion',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código (Ejem: Completa)')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre legible del Estado')),
            ],
            options={
                'verbose_name': 'Estado de Devolución',
                'verbose_name_plural': 'Estados de Devolución',
                'db_table': 's_exp_estadodevolucion',
            },
        ),
        migrations.CreateModel(
            name='EstadoPrestamo',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Código (Ejem: Entregado)')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre legible del Estado')),
            ],
            options={
                'verbose_name': 'Estado de Préstamo',
                'verbose_name_plural': 'Estados de Préstamo',
                'db_table': 's_exp_estadoprestamo',
            },
        ),
        migrations.CreateModel(
            name='TipoAccionLog',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código (Ejem: SOLICITUD_CREADA)')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre legible de la Acción')),
            ],
            options={
                'verbose_name': 'Tipo de Acción (Log)',
                'verbose_name_plural': 'Tipos de Acción (Log)',
                'db_table': 's_exp_tipoaccionlog',
            },
        ),
    ]
