# Generated by Django 5.2.4 on 2026-06-04 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_exp', '0018_poblar_catalogos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='estado',
            field=models.ForeignKey(default='Completa', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='s_exp.estadodevolucion', verbose_name='Estado de Devolución'),
        ),
        migrations.AlterField(
            model_name='loghistorico',
            name='accion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='s_exp.tipoaccionlog', verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.ForeignKey(default='Activo', on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='s_exp.estadoprestamo', verbose_name='Estado del Préstamo'),
        ),
    ]
