# Generated by Django 5.2.4 on 2026-04-06 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0013_etnia_paciente_etnia'),
        ('servicio', '0010_alter_institucion_salud_codigo_sesal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCamaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada')], db_index=True, default='ACTIVA', max_length=10, verbose_name='Estado')),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_cama', to='servicio.cama', verbose_name='Cama')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_cama', to='paciente.paciente', verbose_name='Paciente')),
                ('usuario_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_cama_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de asignacion')),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_cama_cerradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de cierre')),
            ],
            options={
                'verbose_name': 'Asignacion de cama por paciente',
                'verbose_name_plural': 'Asignaciones de cama por paciente',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['cama', 'estado'], name='idx_asig_cama_estado'), models.Index(fields=['paciente', 'estado'], name='idx_asig_paciente_estado')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='chk_asig_fechas_validas')],
            },
        ),
    ]
