# Generated by Django 5.2.4 on 2026-04-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeo_camas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asignacioncamapaciente',
            table='mapeo_camas_asignacion_cama_paciente',
        ),
    ]
