# Generated by Django 5.2.4 on 2026-04-06 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeo_camas', '0002_alter_asignacioncamapaciente_table'),
        ('paciente', '0013_etnia_paciente_etnia'),
        ('servicio', '0010_alter_institucion_salud_codigo_sesal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asignacioncamapaciente',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVA')), fields=('cama',), name='uq_asig_cama_activa'),
        ),
        migrations.AddConstraint(
            model_name='asignacioncamapaciente',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVA')), fields=('paciente',), name='uq_asig_paciente_activo'),
        ),
    ]
