# Generated by Django 5.2.4 on 2026-04-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeo_camas', '0003_asignacioncamapaciente_uq_asig_cama_activa_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asignacioncamapaciente',
            name='uq_asig_cama_activa',
        ),
        migrations.RemoveConstraint(
            model_name='asignacioncamapaciente',
            name='uq_asig_paciente_activo',
        ),
    ]
