# Generated by Django 5.2.4 on 2026-04-06 15:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeo_camas', '0004_remove_asignacioncamapaciente_uq_asig_cama_activa_and_more'),
        ('paciente', '0013_etnia_paciente_etnia'),
        ('servicio', '0010_alter_institucion_salud_codigo_sesal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoCama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('PREALTA', 'Prealta'), ('ALTA', 'Alta'), ('MANTENIMIENTO', 'Mantenimiento / Fuera de servicio'), ('CONSULTA_EXTERNA', 'Consulta externa')], max_length=20, null=True, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('PREALTA', 'Prealta'), ('ALTA', 'Alta'), ('MANTENIMIENTO', 'Mantenimiento / Fuera de servicio'), ('CONSULTA_EXTERNA', 'Consulta externa')], max_length=20, verbose_name='Estado nuevo')),
                ('fecha_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('observacion', models.CharField(blank=True, default='Ingreso (sync)', max_length=255, verbose_name='Observacion')),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_estado', to='servicio.cama', verbose_name='Cama')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_camas', to='paciente.paciente', verbose_name='Paciente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_camas_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de estado de cama',
                'verbose_name_plural': 'Historial de estados de camas',
                'db_table': 'mapeo_camas_historial_estado_cama',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['cama', 'fecha_hora'], name='idx_hist_cama_fecha')],
            },
        ),
    ]
