# Generated by Django 5.2.4 on 2026-04-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeo_camas', '0005_historialestadocama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestadocama',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora'),
        ),
    ]
