# Generated by Django 5.2.4 on 2026-05-26 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeo_camas', '0006_ingreso_operativo_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncamapaciente',
            name='estado',
            field=models.ForeignKey(limit_choices_to={'categoria': 'ESTADO_CAMA'}, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_cama', to='mapeo_camas.estadomapeo', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='detallemapeocama',
            name='estado_actual',
            field=models.ForeignKey(blank=True, limit_choices_to={'categoria': 'ESTADO_CAMA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_mapeo_como_estado', to='mapeo_camas.estadomapeo', verbose_name='Estado actual'),
        ),
        migrations.AlterField(
            model_name='detallemapeocama',
            name='tipo_accion',
            field=models.ForeignKey(limit_choices_to={'categoria': 'TIPO_ACCION'}, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_mapeo_como_accion', to='mapeo_camas.estadomapeo', verbose_name='Tipo de accion'),
        ),
        migrations.AlterField(
            model_name='estadomapeo',
            name='categoria',
            field=models.CharField(choices=[('ESTADO_CAMA', 'Estado de cama'), ('ESTADO_SESION', 'Estado de sesion'), ('TIPO_ACCION', 'Tipo de accion'), ('OBSERVACION', 'Observacion')], max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='historialestadocama',
            name='estado_anterior',
            field=models.ForeignKey(blank=True, limit_choices_to={'categoria': 'ESTADO_CAMA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historiales_como_anterior', to='mapeo_camas.estadomapeo', verbose_name='Estado anterior'),
        ),
        migrations.AlterField(
            model_name='historialestadocama',
            name='estado_nuevo',
            field=models.ForeignKey(limit_choices_to={'categoria': 'ESTADO_CAMA'}, on_delete=django.db.models.deletion.PROTECT, related_name='historiales_como_nuevo', to='mapeo_camas.estadomapeo', verbose_name='Estado nuevo'),
        ),
        migrations.AlterField(
            model_name='mapeosesioncama',
            name='estado',
            field=models.ForeignKey(limit_choices_to={'categoria': 'ESTADO_SESION'}, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_mapeo', to='mapeo_camas.estadomapeo', verbose_name='Estado'),
        ),
    ]
