# Generated by Django 5.2.4 on 2026-05-26 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0005_ingreso_estado'),
        ('mapeo_camas', '0007_alter_asignacioncamapaciente_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacioncamapaciente',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Asignacion de cama', 'verbose_name_plural': 'Asignaciones de cama'},
        ),
        migrations.RemoveIndex(
            model_name='asignacioncamapaciente',
            name='idx_asig_paciente_estado',
        ),
        migrations.RemoveIndex(
            model_name='movimientocama',
            name='idx_mov_paciente_fecha',
        ),
        migrations.RemoveField(
            model_name='asignacioncamapaciente',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='detallemapeocama',
            name='paciente_actual',
        ),
        migrations.RemoveField(
            model_name='historialestadocama',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='movimientocama',
            name='paciente',
        ),
        migrations.AlterField(
            model_name='asignacioncamapaciente',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_cama', to='ingreso.ingreso', verbose_name='Ingreso (pivote operativo)'),
        ),
    ]
