# Generated by Django 5.2.4 on 2026-07-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeo_camas', '0012_alter_mapeosesioncama_observacion_texto_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocama',
            name='tipo_movimiento',
            field=models.CharField(db_index=True, default='MOVIMIENTO', max_length=50, verbose_name='Tipo de movimiento'),
        ),
    ]
