# Generated by Django 5.2.4 on 2026-04-13 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeo_camas', '0012_movimientocama'),
        ('servicio', '0012_estandarizar_estados_cama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeoSesionCama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], db_index=True, default='EN_PROCESO', max_length=20, verbose_name='Estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_mapeo_cama', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesion de mapeo de cama',
                'verbose_name_plural': 'Sesiones de mapeo de cama',
                'db_table': 'mapeo_camas_sesion_cama',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMapeoCama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fue_validada', models.BooleanField(default=False, verbose_name='Fue validada')),
                ('hubo_cambio', models.BooleanField(default=False, verbose_name='Hubo cambio')),
                ('tipo_accion', models.CharField(choices=[('CONFIRMACION', 'Confirmacion'), ('ALTA', 'Alta'), ('CAMBIO', 'Cambio'), ('TRASLADO', 'Traslado'), ('CORRECCION', 'Correccion')], db_index=True, default='CONFIRMACION', max_length=20, verbose_name='Tipo de accion')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('observacion', models.CharField(blank=True, default='', max_length=255, verbose_name='Observacion')),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_mapeo', to='servicio.cama', verbose_name='Cama')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_mapeo_cama', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('sesion_mapeo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='mapeo_camas.mapeosesioncama', verbose_name='Sesion de mapeo')),
            ],
            options={
                'verbose_name': 'Detalle de mapeo de cama',
                'verbose_name_plural': 'Detalles de mapeo de cama',
                'db_table': 'mapeo_camas_detalle_mapeo_cama',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['sesion_mapeo', 'fecha_hora'], name='idx_det_mapeo_sesion_fecha'), models.Index(fields=['cama', 'fecha_hora'], name='idx_det_mapeo_cama_fecha')],
            },
        ),
    ]
