# Generated by Django 5.2.4 on 2026-04-13 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeo_camas', '0013_mapeosesioncama_detallemapeocama'),
        ('paciente', '0018_defuncion_especialidad_defuncion_servicio_auxiliar_and_more'),
        ('servicio', '0012_estandarizar_estados_cama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemapeocama',
            name='estado_actual',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Estado actual'),
        ),
        migrations.AddField(
            model_name='detallemapeocama',
            name='paciente_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_mapeo_actual', to='paciente.paciente', verbose_name='Paciente actual'),
        ),
        migrations.AddField(
            model_name='detallemapeocama',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='mapeosesioncama',
            name='estado',
            field=models.CharField(choices=[('EN_PROGRESO', 'En progreso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], db_index=True, default='EN_PROGRESO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='detallemapeocama',
            index=models.Index(fields=['sesion_mapeo', 'cama'], name='idx_det_mapeo_sesion_cama'),
        ),
    ]
