# Generated by Django 5.2.4 on 2026-04-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeo_camas', '0014_detallemapeocama_estado_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapeosesioncama',
            name='observacion',
            field=models.CharField(blank=True, default='Sin Observaciones', max_length=500, verbose_name='Observacion'),
        ),
    ]
