# Generated by Django 5.2.4 on 2026-04-22 16:35

from django.db import migrations, models


def migrar_alta_a_pre_alta_en_asignacion(apps, schema_editor):
    AsignacionCamaPaciente = apps.get_model("mapeo_camas", "AsignacionCamaPaciente")
    AsignacionCamaPaciente.objects.filter(estado="ALTA").update(estado="PRE_ALTA")


class Migration(migrations.Migration):

    dependencies = [
        ('mapeo_camas', '0015_add_observacion_to_mapeosesioncama'),
    ]

    operations = [
        migrations.RunPython(migrar_alta_a_pre_alta_en_asignacion, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='asignacioncamapaciente',
            name='estado',
            field=models.CharField(choices=[('VACIA', 'Vacia'), ('OCUPADA', 'Ocupada'), ('PRE_ALTA', 'Pre alta'), ('FUERA_SERVICIO', 'Fuera de servicio'), ('CONSULTA_EXTERNA', 'Consulta externa')], db_index=True, default='VACIA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historialestadocama',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('VACIA', 'Vacia'), ('OCUPADA', 'Ocupada'), ('PRE_ALTA', 'Pre alta'), ('ALTA', 'Alta (historico)'), ('FUERA_SERVICIO', 'Fuera de servicio'), ('CONSULTA_EXTERNA', 'Consulta externa')], max_length=20, null=True, verbose_name='Estado anterior'),
        ),
        migrations.AlterField(
            model_name='historialestadocama',
            name='estado_nuevo',
            field=models.CharField(choices=[('VACIA', 'Vacia'), ('OCUPADA', 'Ocupada'), ('PRE_ALTA', 'Pre alta'), ('ALTA', 'Alta (historico)'), ('FUERA_SERVICIO', 'Fuera de servicio'), ('CONSULTA_EXTERNA', 'Consulta externa')], max_length=20, verbose_name='Estado nuevo'),
        ),
    ]
