# Generated by Django 5.2.4 on 2026-04-14 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinico', '0001_initial'),
        ('paciente', '0018_defuncion_especialidad_defuncion_servicio_auxiliar_and_more'),
        ('servicio', '0012_alter_cama_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(db_index=True, max_length=50, unique=True)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados_modificados', to=settings.AUTH_USER_MODEL)),
                ('paciente_ref', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleado', to='paciente.paciente')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalNoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'ADMINISTRATIVO'), (2, 'APOYO'), (3, 'TECNICO'), (4, 'RESPONSABLE'), (5, 'AUXILIAR')], default=1)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_no_clinico_creados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='personal_no_clinico', to='rrhh.empleado')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_no_clinico_modificados', to=settings.AUTH_USER_MODEL)),
                ('servicio_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_no_clinico', to='servicio.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_agendar_citas', models.BooleanField(db_index=True, default=False)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_salud_creados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='personal_salud', to='rrhh.empleado')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_salud', to='servicio.especialidad')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_salud_modificados', to=settings.AUTH_USER_MODEL)),
                ('servicio_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_salud', to='servicio.unidad')),
                ('tipo_personal_salud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_salud', to='clinico.tipo_personal_salud')),
            ],
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['primer_apellido'], name='rrhh_emplea_primer__2b7ada_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['dni'], name='rrhh_emplea_dni_3879ac_idx'),
        ),
        migrations.AddIndex(
            model_name='personalsalud',
            index=models.Index(fields=['puede_agendar_citas'], name='rrhh_person_puede_a_c59523_idx'),
        ),
    ]
