# Generated by Django 5.2.4 on 2026-04-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalsalud',
            old_name='especialidad',
            new_name='area_atencion',
        ),
    ]
