# Generated by Django 5.2.4 on 2026-04-21 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0002_especialidad'),
        ('rrhh', '0002_rename_especialidad_personalsalud_area_atencion'),
        ('servicio', '0014_alter_area_atencion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalsalud',
            name='area_atencion',
        ),
        migrations.AddField(
            model_name='personalsalud',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_salud_especialidad', to='clinico.especialidad'),
        ),
        migrations.AlterField(
            model_name='personalsalud',
            name='empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='personal_salud_empleado', to='rrhh.empleado'),
        ),
        migrations.AlterField(
            model_name='personalsalud',
            name='servicio_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_salud_unidad', to='servicio.unidad'),
        ),
        migrations.AlterField(
            model_name='personalsalud',
            name='tipo_personal_salud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_salud_tipo', to='clinico.tipo_personal_salud'),
        ),
    ]
