# Generated by Django 5.2.4 on 2026-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_remove_personalsalud_area_atencion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada_laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jornada_laboral', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la jornada')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
            ],
            options={
                'verbose_name': 'Jornada Laboral',
                'verbose_name_plural': 'Jornadas Laborales',
                'ordering': ['nombre_jornada_laboral'],
            },
        ),
    ]
