# Generated by Django 5.2.4 on 2026-05-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_jornada_laboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalsalud',
            name='estado',
            field=models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1),
        ),
    ]
