# Generated by Django 5.2.4 on 2026-08-28 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0004_tipo_atencion_nombre_corto_tipo_atencion'),
        ('rrhh', '0005_personalsalud_estado'),
        ('servicio', '0018_alter_cama_estado_alter_unidad_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personalsalud',
            name='puede_operar',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='personalsalud',
            index=models.Index(fields=['puede_operar'], name='rrhh_person_puede_o_ed29bd_idx'),
        ),
    ]
