# Generated by Django 5.0.11 on 2025-07-15 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('digitador', 'Digitador'), ('auditor', 'Auditor')], max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.unidad')),
            ],
            options={
                'unique_together': {('usuario', 'unidad')},
            },
        ),
    ]
