# Generated by Django 5.0.11 on 2025-08-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilunidad',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('digitador', 'Digitador'), ('auditor', 'Auditor'), ('visitante', 'Visitante')], max_length=20),
        ),
    ]
