# Generated by Django 5.2.4 on 2026-04-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_perfilunidad_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilunidad',
            name='alcance',
            field=models.PositiveSmallIntegerField(choices=[(1, 'POR UNIDAD'), (2, 'GLOBAL')], default=1),
        ),
    ]
