# Generated by Django 5.2.4 on 2026-04-09 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0012_alter_cama_estado_and_more'),
        ('usuario', '0003_perfilunidad_alcance'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilunidad',
            name='servicio_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicio.unidad'),
        ),
    ]
