# Generated by Django 5.2.4 on 2026-04-09 21:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0012_alter_cama_estado_and_more'),
        ('usuario', '0004_perfilunidad_servicio_unidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='perfilunidad',
            unique_together={('usuario', 'servicio_unidad', 'alcance')},
        ),
        migrations.RemoveField(
            model_name='perfilunidad',
            name='unidad',
        ),
    ]
