# Generated by Django 5.2.4 on 2026-03-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_perfilunidad_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilunidad',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('digitador', 'Digitador'), ('auditor', 'Auditor'), ('visitante', 'Visitante'), ('exp_solicitante', 'Solicitante')], max_length=20),
        ),
    ]
