# Generated by Django 5.2.4 on 2026-05-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_perfilunidad_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unidad',
        ),
    ]
