# Generated by Django 5.2.4 on 2026-04-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_perfilunidad_rol'),
        ('usuario', '0006_alter_perfilunidad_rol'),
    ]

    operations = [
    ]
