# Generated by Django 5.2.4 on 2026-04-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_merge_20260413_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilunidad',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('digitador', 'Digitador'), ('auditor', 'Auditor'), ('visitante', 'Visitante'), ('directivo', 'Directivo')], max_length=20),
        ),
    ]
