# Generated by Django 5.2.4 on 2026-05-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_delete_unidad'),
        ('usuario', '0008_alter_perfilunidad_rol'),
    ]

    operations = [
    ]
