# Generated by Django 5.0.11 on 2025-03-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre_zona', models.CharField(max_length=60, verbose_name='Nombre Zona')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['codigo'],
            },
        ),
    ]
