# Generated by Django 5.0.11 on 2025-03-19 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(max_length=60, verbose_name='Nombre Sala')),
                ('sexo_esperado', models.SmallIntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')], default=1, verbose_name='Sexo Esperado')),
                ('edad_minima_meses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad Mínima (meses)')),
                ('edad_maxima_meses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad Máxima (meses)')),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha Editado')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salas_creadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salas_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nombre_sala'],
            },
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('numero_cama', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de Cama')),
                ('estado', models.IntegerField(choices=[(1, 'Disponible'), (2, 'Ocupada'), (3, 'En Mantenimiento')], default=1, verbose_name='Estado de la Cama')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha Editado')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camas_creadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camas_modificadas', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camas_sala', to='servicio.sala')),
            ],
            options={
                'verbose_name': 'Cama',
                'verbose_name_plural': 'Camas',
                'ordering': ['numero_cama'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=60, verbose_name='Nombre Servicio')),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre_servicio'],
            },
        ),
        migrations.AddField(
            model_name='sala',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salas_servicio', to='servicio.servicio'),
        ),
    ]
