# Generated by Django 5.0.11 on 2025-03-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_sala_cama_servicio_sala_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='sexo_esperado',
            field=models.SmallIntegerField(choices=[(0, 'Indiferente'), (1, 'Masculino'), (2, 'Femenino')], default=1, verbose_name='Sexo Esperado'),
        ),
    ]
