# Generated by Django 5.0.11 on 2025-03-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_alter_sala_sexo_esperado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='nombre_corto',
            field=models.CharField(default='DD', max_length=10, verbose_name='Nombre Corto Servicio'),
        ),
    ]
