# Generated by Django 5.0.11 on 2025-04-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_servicio_nombre_corto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='nombre_corto',
            field=models.CharField(default='NA', max_length=10, verbose_name='Nombre Corto Servicio'),
        ),
    ]
