# Generated by Django 5.0.1 on 2025-05-18 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_alter_servicio_nombre_corto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=100, unique=True)),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especialidades', to='servicio.servicio')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre_especialidad'],
            },
        ),
    ]
