# Generated by Django 5.0.11 on 2025-07-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosAux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio_a', models.CharField(max_length=100, unique=True)),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Servicio Auxiliar',
                'verbose_name_plural': 'Servicios Auxiliares',
                'ordering': ['nombre_servicio_a'],
            },
        ),
    ]
