# Generated by Django 5.2.4 on 2025-11-09 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_serviciosaux'),
        ('ubicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='nombre_corto_especialidad',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='nombre_corto_sala',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='serviciosaux',
            name='nombre_corto_servicio_a',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        )
        ]
