# Generated by Django 5.2.4 on 2025-11-09 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0008_gestor_nivel_complejidad_institucional_and_more'),
        ('ubicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gestor', models.CharField(max_length=30, unique=True, verbose_name='Nombre del gestor')),
                ('detalle_gestor', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Detalle del gestor')),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Gestor',
                'verbose_name_plural': 'Gestores',
                'ordering': ['nombre_gestor'],
            },
        ),
        migrations.CreateModel(
            name='Nivel_complejidad_institucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_complejidad', models.SmallIntegerField(verbose_name='Nivel de complejidad')),
                ('siglas', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Siglas del nivel de complejidad')),
                ('detalle_nivel_complejidad', models.CharField(max_length=100, unique=True, verbose_name='Detalle del nivel de complejidad')),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Nivel de complejidad institucional',
                'verbose_name_plural': 'Niveles de complejidad institucional',
                'ordering': ['nivel_complejidad'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor_salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor_salud', models.CharField(max_length=30, unique=True, verbose_name='Nombre del proveedor de salud')),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Proveedor de salud',
                'verbose_name_plural': 'Proveedores de salud',
                'ordering': ['nombre_proveedor_salud'],
            },
        ),
        migrations.CreateModel(
            name='Region_salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveSmallIntegerField(unique=True)),
                ('nombre_region_salud', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la region de salud')),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Region Sanitaria salud',
                'verbose_name_plural': 'Region Sanitaria salud',
                'ordering': ['nombre_region_salud'],
            },
        ),
        migrations.CreateModel(
            name='Institucion_salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sesal', models.IntegerField(null=True, unique=True, verbose_name='Codigo SESAL')),
                ('nombre_institucion_salud', models.CharField(max_length=50, verbose_name='Nombre de la institucion de salud')),
                ('nivel_atencion', models.SmallIntegerField(choices=[(1, 'Primer nivel'), (2, 'Segundo nivel'), (3, 'Otros')], default=1, verbose_name='Nivel de atencion')),
                ('centralizado', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=True, verbose_name='Centralizado')),
                ('telefono', models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefono')),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha Editado')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instituciones_salud', to='ubicacion.sector')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestores', to='servicio.gestor')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituciones_modificadas', to=settings.AUTH_USER_MODEL)),
                ('nivel_complejidad_institucional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveles', to='servicio.nivel_complejidad_institucional')),
                ('proveedor_salud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='servicio.proveedor_salud')),
                ('region_salud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regiones', to='servicio.region_salud')),
            ],
            options={
                'verbose_name': 'Institucion de salud',
                'verbose_name_plural': 'Instituciones de salud',
                'ordering': ['nombre_institucion_salud'],
            },
        ),
    ]
