# Generated by Django 5.2.4 on 2025-11-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0009_gestor_nivel_complejidad_institucional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion_salud',
            name='codigo_sesal',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Codigo SESAL'),
        ),
    ]
