# Generated by Django 5.2.4 on 2026-04-06 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0010_alter_institucion_salud_codigo_sesal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cubiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Numero de Cubiculo')),
                ('nombre_cubiculo', models.CharField(max_length=100, verbose_name='Nombre Cubiculo')),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cubiculos', to='servicio.sala')),
            ],
            options={
                'verbose_name': 'Cubiculo',
                'verbose_name_plural': 'Cubiculos',
                'ordering': ['sala', 'numero'],
                'unique_together': {('sala', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='cama',
            name='cubiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='camas', to='servicio.cubiculo'),
        ),
    ]
