# Generated by Django 5.2.4 on 2026-04-09 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0011_cubiculo_cama_cubiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cama',
            name='estado',
            field=models.IntegerField(choices=[(1, 'DISPONIBLE'), (2, 'OCUPADA'), (3, 'EN MANTENIMIENTO')], default=1, verbose_name='Estado de la Cama'),
        ),
        migrations.AlterField(
            model_name='institucion_salud',
            name='nivel_atencion',
            field=models.SmallIntegerField(choices=[(1, 'PRIMER NIVEL'), (2, 'SEGUNDO NIVEL'), (3, 'OTROS')], default=1, verbose_name='Nivel de atencion'),
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=100, unique=True)),
                ('nombre_corto_unidad', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'CLINICA'), (2, 'ADMINISTRATIVA'), (3, 'APOYO')], default=1)),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha Editado')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_creadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
