# Generated by Django 5.2.4 on 2026-04-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0008_alter_atencion_paciente'),
        ('imagenologia', '0004_alter_evaluacionrx_creado_por_and_more'),
        ('paciente', '0018_defuncion_especialidad_defuncion_servicio_auxiliar_and_more'),
        ('referencia', '0001_initial'),
        ('rrhh', '0001_initial'),
        ('servicio', '0012_alter_cama_estado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especialidad',
            new_name='Area_atencion',
        ),
    ]
