# Generated by Django 5.2.4 on 2026-04-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0013_rename_especialidad_area_atencion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area_atencion',
            options={'ordering': ['nombre_area_atencion'], 'verbose_name': 'Area atencion', 'verbose_name_plural': 'Areas atencion'},
        ),
        migrations.RenameField(
            model_name='area_atencion',
            old_name='nombre_especialidad',
            new_name='nombre_area_atencion',
        ),
        migrations.RenameField(
            model_name='area_atencion',
            old_name='nombre_corto_especialidad',
            new_name='nombre_corto_area_atencion',
        ),
        migrations.AlterField(
            model_name='area_atencion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicio_Area_atencion', to='servicio.servicio'),
        ),
    ]
