# Generated by Django 5.2.4 on 2026-04-21 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0014_alter_area_atencion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad_clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
                ('area_atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicio.area_atencion')),
                ('establecimiento_ext', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicio.institucion_salud')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicio.sala')),
                ('servicio_aux', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicio.serviciosaux')),
            ],
            options={
                'verbose_name': 'Punto de atencion clinico',
                'verbose_name_plural': 'Puntos de atencion clinicos',
                'constraints': [models.UniqueConstraint(condition=models.Q(('area_atencion__isnull', False)), fields=('area_atencion',), name='unique_area_atencion_uc'), models.UniqueConstraint(condition=models.Q(('sala__isnull', False)), fields=('sala',), name='unique_sala_uc'), models.UniqueConstraint(condition=models.Q(('servicio_aux__isnull', False)), fields=('servicio_aux',), name='unique_servicio_aux_uc'), models.UniqueConstraint(condition=models.Q(('establecimiento_ext__isnull', False)), fields=('establecimiento_ext',), name='unique_est_ext_uc')],
            },
        ),
    ]
