# Generated by Django 5.2.4 on 2026-04-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0012_estandarizar_estados_cama'),
        ('servicio', '0014_alter_area_atencion_options_and_more'),
    ]

    operations = [
    ]
