# Generated by Django 5.2.4 on 2026-04-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0015_unidad_clinica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad_clinica',
            options={'verbose_name': 'Unidad Clinica', 'verbose_name_plural': 'Unidades Clinicas'},
        ),
        migrations.RemoveConstraint(
            model_name='unidad_clinica',
            name='unique_area_atencion_uc',
        ),
        migrations.RemoveConstraint(
            model_name='unidad_clinica',
            name='unique_sala_uc',
        ),
        migrations.RemoveConstraint(
            model_name='unidad_clinica',
            name='unique_servicio_aux_uc',
        ),
        migrations.RemoveConstraint(
            model_name='unidad_clinica',
            name='unique_est_ext_uc',
        ),
        migrations.AddField(
            model_name='institucion_salud',
            name='es_unidad_clinica',
            field=models.BooleanField(default=False),
        ),
    ]
