# Generated by Django 5.2.4 on 2026-05-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0015_merge_20260422_1515'),
        ('servicio', '0016_alter_unidad_clinica_options_and_more'),
    ]

    operations = [
    ]
