# Generated by Django 5.2.4 on 2026-07-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0017_merge_20260507_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cama',
            name='estado',
            field=models.IntegerField(choices=[(1, 'DISPONIBLE'), (2, 'OCUPADA'), (3, 'EN MANTENIMIENTO')], default=1, verbose_name='Estado de la Cama'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(2, 'ADMINISTRATIVA'), (3, 'APOYO')], default=2),
        ),
    ]
