# Generated by Django 5.2.4 on 2026-07-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0018_alter_cama_estado'),
        ('servicio', '0018_alter_cama_estado_alter_unidad_tipo'),
    ]

    operations = [
    ]
