# Generated by Django 5.0.1 on 2025-05-06 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0004_paciente_fecha_sai_paciente_sai'),
        ('servicio', '0005_alter_servicio_nombre_corto'),
        ('ubicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numero de identificacion')),
                ('primer_nombre', models.CharField(max_length=100, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo nombre')),
                ('primer_apellido', models.CharField(max_length=100, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo apellido')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ubicacion.sector', verbose_name='Domicilio')),
            ],
            options={
                'verbose_name': 'Acompañante',
                'verbose_name_plural': 'Acompañantes',
                'ordering': ['primer_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_egreso', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha Editado')),
                ('acompaniante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acompaniantes_ingreso', to='ingreso.acompanante')),
                ('cama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicio.cama')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingreso_registrado', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingreso_modificadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_ingresados', to='paciente.paciente', verbose_name='Paciente')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_sala', to='servicio.sala')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.zona')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionIngresoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_ingresos_modificadas', to=settings.AUTH_USER_MODEL)),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_ingresos_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recepción de ingreso',
                'verbose_name_plural': 'Recepciones de ingresos',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionIngresoDetalleSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepcion_detalles', to='ingreso.ingreso')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ingreso.recepcioningresosala')),
            ],
            options={
                'verbose_name': 'Detalle de recepción',
                'verbose_name_plural': 'Detalles de recepción',
                'unique_together': {('recepcion', 'ingreso')},
            },
        ),
    ]
