# Generated by Django 5.0.1 on 2025-05-06 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recepcioningresosala',
            options={'ordering': ['-fecha_recepcion'], 'verbose_name': 'Recepción de ingreso sala', 'verbose_name_plural': 'Recepciones de ingresos sala'},
        ),
        migrations.AddField(
            model_name='ingreso',
            name='fecha_recepcion_sdgi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recepcioningresodetallesala',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepcion_detalles_sala', to='ingreso.ingreso'),
        ),
        migrations.AlterField(
            model_name='recepcioningresosala',
            name='modificado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_ingresos_sala_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recepcioningresosala',
            name='recibido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_ingresos_sala_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecepcionIngresoSDGI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_ingresos_sdgi_modificadas', to=settings.AUTH_USER_MODEL)),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_ingresos_sdgi_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recepción de ingreso SDGI',
                'verbose_name_plural': 'Recepciones de ingresos SDGI',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionIngresoDetalleSDGI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepcion_detalles_sdgi', to='ingreso.ingreso')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ingreso.recepcioningresosdgi')),
            ],
            options={
                'verbose_name': 'Detalle de recepción SDGI',
                'verbose_name_plural': 'Detalles de recepción SDGI',
                'unique_together': {('recepcion', 'ingreso')},
            },
        ),
    ]
