# Generated by Django 5.0.1 on 2025-05-18 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0002_alter_recepcioningresosala_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReversionRecepcionIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_reversion', models.DateTimeField(auto_now_add=True)),
                ('reverso_recepcion_sala', models.BooleanField(default=False)),
                ('reverso_recepcion_sdgi', models.BooleanField(default=False)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversiones', to='ingreso.ingreso')),
                ('revertido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reversión de Ingreso',
                'verbose_name_plural': 'Reversiones de Ingresos',
            },
        ),
    ]
