# Generated by Django 5.0.11 on 2025-07-02 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0003_reversionrecepcioningreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
