# Generated by Django 5.0.11 on 2025-08-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0004_alter_ingreso_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='estado',
            field=models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado'),
        ),
    ]
