# Generated by Django 6.0.5 on 2026-06-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_alter_dispositivo_marca_alter_dispositivo_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='inventario_bienes_nacionales',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
