# Generated by Django 6.0.5 on 2026-06-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_dispositivo_tipo_tecnologia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignaciondispositivo',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Asignación de equipo', 'verbose_name_plural': 'Asignaciones de equipos'},
        ),
        migrations.AlterModelOptions(
            name='dispositivo',
            options={'ordering': ['nombre', 'numero_serie'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='tipodispositivo',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de equipo', 'verbose_name_plural': 'Tipos de equipo'},
        ),
    ]
