# Generated by Django 6.0.5 on 2026-06-22 16:33

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0007_catalogos_marca_modelo_y_ficha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dispositivo',
            name='bio_disp_frecuencia_positiva',
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='frecuencia_mantenimiento_meses',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cantidad de meses entre mantenimientos preventivos.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.CheckConstraint(condition=models.Q(('frecuencia_mantenimiento_meses__isnull', True), ('frecuencia_mantenimiento_meses__gt', 0), _connector='OR'), name='bio_disp_frecuencia_positiva'),
        ),
    ]
