# Generated by Django 6.0.5 on 2026-06-29 15:38

import django.db.models.deletion
from django.db import migrations, models


def crear_catalogos_indefinidos(apps, schema_editor):
    AreaGestora = apps.get_model('equipos', 'AreaGestora')
    ColorDispositivo = apps.get_model('equipos', 'ColorDispositivo')
    Dispositivo = apps.get_model('equipos', 'Dispositivo')

    area_indefinida, _ = AreaGestora.objects.get_or_create(
        nombre='INDEFINIDO',
        defaults={'descripcion': 'Valor usado cuando el area gestora no aplica.'},
    )
    color_indefinido, _ = ColorDispositivo.objects.get_or_create(
        nombre='INDEFINIDO',
        defaults={'descripcion': 'Valor usado cuando el color no aplica.'},
    )

    Dispositivo.objects.filter(area_gestora__isnull=True).update(
        area_gestora=area_indefinida
    )
    Dispositivo.objects.filter(color__isnull=True).update(color=color_indefinido)


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0010_bajadispositivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaGestora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Area gestora',
                'verbose_name_plural': 'Areas gestoras',
                'db_table': 'equipo_area_gestora',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ColorDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Color de equipo',
                'verbose_name_plural': 'Colores de equipo',
                'db_table': 'equipo_color_dispositivo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='area_gestora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='equipos.areagestora'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='equipos.colordispositivo'),
        ),
        migrations.RunPython(crear_catalogos_indefinidos, migrations.RunPython.noop),
    ]
