# Generated by Django 5.2.4 on 2026-07-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0016_datetime_sin_microsegundos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajadispositivo',
            name='comentario_responsable',
            field=models.TextField(blank=True, default='', verbose_name='Comentario del responsable de mantenimiento'),
        ),
        migrations.AddField(
            model_name='bajadispositivo',
            name='ficha_firmada_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID de la ficha firmada'),
        ),
    ]
