# Generated by Django 5.2.4 on 2026-07-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0018_bajadispositivo_habitacion_estancia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajadispositivo',
            name='comentario_responsable',
        ),
    ]
