# Generated by Django 5.2.4 on 2026-07-27 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0019_remove_bajadispositivo_comentario_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajoBajaDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_baja_dispositivos_creadas', to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='orden_trabajo_baja', to='equipos.dispositivo')),
            ],
            options={
                'verbose_name': 'Orden de trabajo para baja',
                'verbose_name_plural': 'Órdenes de trabajo para baja',
                'db_table': 'equipo_orden_trabajo_baja',
                'ordering': ['-fecha_creado'],
            },
        ),
    ]
