# Generated by Django 5.2.4 on 2026-07-31 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Agrega el color secundario, opcional, a los equipos.

    Es un AddField con null=True y sin valor por defecto, asi que los equipos
    ya registrados quedan con color_secundario = NULL sin necesidad de tocar
    una sola fila. No se crea catalogo nuevo: apunta a la misma tabla
    equipo_color_dispositivo que ya usa el color principal.
    """

    dependencies = [
        ('equipos', '0021_modelo_pertenece_a_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='color_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos_color_secundario', to='equipos.colordispositivo', verbose_name='Color secundario'),
        ),
    ]
