# Generated by Django 5.2.4 on 2026-08-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0022_dispositivo_color_secundario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajadispositivo',
            name='responsable_peticion',
        ),
    ]
