# Generated by Django 5.2.4 on 2026-08-03 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0023_remove_responsable_peticion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajadispositivo',
            name='fecha_baja',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False, verbose_name='Fecha de baja'),
        ),
    ]
