# Generated by Django 5.2.4 on 2026-08-03 21:32

from django.conf import settings
from django.db import migrations, models


def migrar_duracion_garantia(apps, schema_editor):
    """Convierte fechas historicas a la opcion de uno o dos anios mas cercana."""
    Dispositivo = apps.get_model("equipos", "Dispositivo")

    for dispositivo in Dispositivo.objects.exclude(
        fin_garantia__isnull=True
    ).iterator():
        inicio = dispositivo.fecha_instalacion
        if not inicio and dispositivo.fecha_creado:
            inicio = dispositivo.fecha_creado.date()

        # Una fecha de fin implica que si existia garantia. Cuando falta su
        # inicio se conserva con la duracion minima en vez de descartarla.
        if not inicio:
            duracion_anios = 1
        else:
            duracion_dias = (dispositivo.fin_garantia - inicio).days
            duracion_anios = 1 if duracion_dias <= 548 else 2

        Dispositivo.objects.filter(pk=dispositivo.pk).update(
            garantia_anios=duracion_anios
        )


def restaurar_fecha_garantia(apps, schema_editor):
    """Reconstruye una fecha aproximada si se revierte esta migracion."""
    Dispositivo = apps.get_model("equipos", "Dispositivo")

    for dispositivo in Dispositivo.objects.exclude(garantia_anios=0).iterator():
        inicio = dispositivo.fecha_instalacion
        if not inicio and dispositivo.fecha_creado:
            inicio = dispositivo.fecha_creado.date()
        if not inicio:
            continue

        try:
            fin_garantia = inicio.replace(
                year=inicio.year + dispositivo.garantia_anios
            )
        except ValueError:
            # El 29 de febrero termina el 28 cuando el anio final no es bisiesto.
            fin_garantia = inicio.replace(
                month=2,
                day=28,
                year=inicio.year + dispositivo.garantia_anios,
            )

        Dispositivo.objects.filter(pk=dispositivo.pk).update(
            fin_garantia=fin_garantia
        )


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0024_alter_bajadispositivo_fecha_baja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dispositivo',
            name='bio_disp_garantia_fecha_valida',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='garantia_anios',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin garantía'), (1, '1 año'), (2, '2 años')], default=0, verbose_name='Garantía'),
        ),
        migrations.RunPython(
            migrar_duracion_garantia,
            restaurar_fecha_garantia,
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='fin_garantia',
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.CheckConstraint(condition=models.Q(('garantia_anios__in', [0, 1, 2])), name='equipo_garantia_anios_valida'),
        ),
    ]
