# Generated by Django 5.2.4 on 2026-08-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0031_procedencia_y_origen_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedencia',
            name='telefono_alterno',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
