# Generated by Django 5.2.4 on 2026-08-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0033_datetime_sin_microsegundos_tablas_nuevas'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pausagarantia',
            name='equipo_pausa_retorno_no_anterior',
        ),
    ]
