# Generated by Django 5.2.4 on 2026-09-25 21:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0034_remove_pausagarantia_equipo_pausa_retorno_no_anterior'),
        ('expediente', '0011_remove_expedienteubicacion_expubic_clinica_xor_noclinica'),
        ('rrhh', '0005_personalsalud_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Categoria de equipo',
                'verbose_name_plural': 'Categorias de equipo',
                'db_table': 'equipo_categoria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Ubicacion fisica',
                'verbose_name_plural': 'Ubicaciones fisicas',
                'db_table': 'equipo_ubicacion_fisica',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='tipodispositivo',
            options={'ordering': ['categoria__nombre', 'nombre'], 'verbose_name': 'Tipo de equipo', 'verbose_name_plural': 'Tipos de equipo'},
        ),
        migrations.RemoveConstraint(
            model_name='asignaciondispositivo',
            name='bio_asig_una_ubicacion',
        ),
        migrations.RemoveIndex(
            model_name='asignaciondispositivo',
            name='bio_asig_area_fecha_fin_idx',
        ),
        migrations.RemoveIndex(
            model_name='asignaciondispositivo',
            name='bio_asig_unidad_fecha_fin_idx',
        ),
        migrations.RemoveField(
            model_name='asignaciondispositivo',
            name='area_clinica',
        ),
        migrations.RemoveField(
            model_name='asignaciondispositivo',
            name='unidad_no_clinica',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='color_secundario',
        ),
        migrations.AddField(
            model_name='asignaciondispositivo',
            name='ubicacion',
            field=models.ForeignKey(help_text='Punto clínico o no clínico donde queda cargado el equipo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_dispositivos_equipos', to='expediente.expedienteubicacion', verbose_name='Unidad o área'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='colores',
            field=models.ManyToManyField(blank=True, db_table='equipo_dispositivo_color', related_name='dispositivos', to='equipos.colordispositivo', verbose_name='Colores'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='fecha_inicio_garantia',
            field=models.DateField(blank=True, help_text='Día en que empezó a correr la garantía.', null=True, verbose_name='Inicio de garantía'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='garantia_meses',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Meses de cobertura. Vacío si el contrato solo da la fecha.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración de garantía (meses)'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='vida_util_anios',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Vida útil (años)'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='criticidad',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], db_index=True, default=2),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.CheckConstraint(condition=models.Q(('garantia_meses__isnull', True), ('garantia_meses__gt', 0), _connector='OR'), name='equipo_disp_garantia_meses_positiva'),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.CheckConstraint(condition=models.Q(('vida_util_anios__isnull', True), ('vida_util_anios__gt', 0), _connector='OR'), name='equipo_disp_vida_util_positiva'),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_inicio_garantia__isnull', True), ('fecha_fin_garantia__isnull', True), ('fecha_fin_garantia__gte', models.F('fecha_inicio_garantia')), _connector='OR'), name='equipo_disp_garantia_fechas_coherentes'),
        ),
        migrations.AddField(
            model_name='tipodispositivo',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos', to='equipos.categoriaequipo', verbose_name='Categoria principal'),
        ),
        migrations.AddField(
            model_name='tipodispositivo',
            name='categorias_secundarias',
            field=models.ManyToManyField(blank=True, related_name='tipos_secundarios', to='equipos.categoriaequipo', verbose_name='Categorias secundarias'),
        ),
        migrations.AddField(
            model_name='asignaciondispositivo',
            name='ubicacion_fisica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_dispositivos_equipos', to='equipos.ubicacionfisica', verbose_name='Ubicación física'),
        ),
        migrations.AddIndex(
            model_name='asignaciondispositivo',
            index=models.Index(fields=['ubicacion', 'fecha_fin'], name='equipo_asig_ubicacion_fin_idx'),
        ),
    ]
