# Generated by Django 5.0.1 on 2025-05-18 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0004_paciente_fecha_sai_paciente_sai'),
        ('servicio', '0005_alter_servicio_nombre_corto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(max_length=50, verbose_name='Numero de expediente')),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atencion_medica_creada', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atencion_medica_modificada', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente', verbose_name='Paciente')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Atención Medica',
                'verbose_name_plural': 'Atenciones Medicas',
                'ordering': ['-fecha_atencion'],
            },
        ),
    ]
