# Generated by Django 5.0.1 on 2025-05-18 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0001_initial'),
        ('servicio', '0006_especialidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atencion',
            options={'ordering': ['-fecha_atencion'], 'verbose_name': 'Atención', 'verbose_name_plural': 'Atenciones'},
        ),
        migrations.RemoveField(
            model_name='atencion',
            name='sala',
        ),
        migrations.AddField(
            model_name='atencion',
            name='especialidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='servicio.especialidad', verbose_name='Especialidad'),
            preserve_default=False,
        ),
    ]
