# Generated by Django 5.0.1 on 2025-05-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0002_alter_atencion_options_remove_atencion_sala_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='expediente',
        ),
    ]
