# Generated by Django 5.0.11 on 2025-05-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0003_remove_atencion_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
