# Generated by Django 5.0.11 on 2025-05-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0004_atencion_fecha_recepcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='fecha_atencion',
            field=models.DateTimeField(),
        ),
    ]
