# Generated by Django 5.0.11 on 2025-05-21 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0005_alter_atencion_fecha_atencion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_atenciones_modificadas', to=settings.AUTH_USER_MODEL)),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_atenciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recepción de atencion',
                'verbose_name_plural': 'Recepciones de atenciones',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionAtencionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepcion_detalles_atencion', to='atencion.atencion')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='atencion.recepcionatencion')),
            ],
            options={
                'verbose_name': 'Detalle de recepción atencion',
                'verbose_name_plural': 'Detalles de recepción de atenciones',
                'unique_together': {('recepcion', 'atencion')},
            },
        ),
    ]
