# Generated by Django 5.0.11 on 2025-05-26 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0006_recepcionatencion_recepcionatenciondetalle'),
        ('paciente', '0005_paciente_orden_gemelar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente', verbose_name='atenciones'),
        ),
    ]
