# Generated by Django 5.0.11 on 2025-05-26 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0007_alter_atencion_paciente'),
        ('paciente', '0005_paciente_orden_gemelar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='paciente.paciente', verbose_name='Paciente'),
        ),
    ]
