# Generated by Django 5.2.4 on 2026-04-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0008_alter_atencion_paciente'),
        ('servicio', '0014_alter_area_atencion_options_and_more'),
    ]

    operations = [
    migrations.RenameField(
        model_name='atencion',
        old_name='especialidad',
        new_name='area_atencion',
    ),
]
