# Generated by Django 5.2.4 on 2026-04-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0009_remove_atencion_especialidad_atencion_area_atencion'),
        ('servicio', '0014_alter_area_atencion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='area_atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.area_atencion', verbose_name='Area Atencion'),
        ),
    ]
