# Generated by Django 5.2.4 on 2026-08-06 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_transporte_hospitalario', '0014_tipo_viaje_entero_y_sin_viatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucionviaje',
            name='litros_cargados_salida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ejecucionviaje',
            name='observaciones_retorno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ejecucionviaje',
            name='observaciones_salida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ejecucionviaje',
            name='precio_litro_salida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ejecucionviaje',
            name='total_combustible',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='ejecucionviaje',
            name='combustible_retorno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ejecucionviaje',
            name='combustible_salida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ejecucionviaje',
            name='fecha_retorno',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ejecucionviaje',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ejecucionviaje',
            name='kilometraje_retorno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ejecucionviaje',
            name='kilometraje_salida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='centro_costo',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
