# Generated by Django 6.0.5 on 2026-06-12 20:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0003_remove_personalsalud_area_atencion_and_more'),
        ('servicio', '0016_alter_unidad_clinica_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Tipo de dispositivo',
                'verbose_name_plural': 'Tipos de dispositivo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=120)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Operativo'), (2, 'En mantenimiento'), (3, 'Fuera de servicio'), (4, 'Dado de baja')], db_index=True, default=1)),
                ('criticidad', models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], db_index=True)),
                ('frecuencia_mantenimiento_meses', models.PositiveSmallIntegerField(help_text='Cantidad de meses entre mantenimientos preventivos.', validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_instalacion', models.DateField()),
                ('fin_garantia', models.DateField(blank=True, null=True)),
                ('costo_adquisicion', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos_biomedicos_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos_biomedicos_modificados', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='equipos_biomedicos.tipodispositivo')),
            ],
            options={
                'verbose_name': 'Dispositivo biomédico',
                'verbose_name_plural': 'Dispositivos biomédicos',
                'ordering': ['nombre', 'numero_serie'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('area_clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_dispositivos_biomedicos', to='servicio.area_atencion')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_dispositivos_biomedicos_creadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_dispositivos_biomedicos_modificadas', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_dispositivos_biomedicos', to='rrhh.empleado')),
                ('unidad_no_clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_dispositivos_biomedicos', to='servicio.unidad')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='equipos_biomedicos.dispositivo')),
            ],
            options={
                'verbose_name': 'Asignación de dispositivo biomédico',
                'verbose_name_plural': 'Asignaciones de dispositivos biomédicos',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['dispositivo', 'fecha_fin'], name='bio_asig_disp_fecha_fin_idx'), models.Index(fields=['area_clinica', 'fecha_fin'], name='bio_asig_area_fecha_fin_idx'), models.Index(fields=['unidad_no_clinica', 'fecha_fin'], name='bio_asig_unidad_fecha_fin_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('area_clinica__isnull', False), ('unidad_no_clinica__isnull', True)), models.Q(('area_clinica__isnull', True), ('unidad_no_clinica__isnull', False)), _connector='OR'), name='bio_asig_una_ubicacion'), models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='bio_asig_fechas_validas')],
            },
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['estado', 'criticidad'], name='bio_disp_estado_criticidad_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.CheckConstraint(condition=models.Q(('frecuencia_mantenimiento_meses__gt', 0)), name='bio_disp_frecuencia_positiva'),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.CheckConstraint(condition=models.Q(('costo_adquisicion__gte', 0)), name='bio_disp_costo_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.CheckConstraint(condition=models.Q(('fin_garantia__isnull', True), ('fin_garantia__gte', models.F('fecha_instalacion')), _connector='OR'), name='bio_disp_garantia_fecha_valida'),
        ),
    ]
