# Generated by Django 6.0.5 on 2026-06-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_biomedicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='marca',
            field=models.CharField(blank=True, default='Indefinido', max_length=80),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='modelo',
            field=models.CharField(blank=True, default='Indefinido', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
