# Generated by Django 6.0.5 on 2026-06-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_biomedicos', '0003_dispositivo_inventario_bienes_nacionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='tipo_tecnologia',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Electrónico'), (2, 'No electrónico')], db_index=True, null=True),
        ),
    ]
