# Generated by Django 6.0.5 on 2026-06-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_biomedicos', '0005_alter_asignaciondispositivo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asignaciondispositivo',
            table='equipo_asignacion_dispositivo',
        ),
        migrations.AlterModelTable(
            name='dispositivo',
            table='equipo_dispositivo',
        ),
        migrations.AlterModelTable(
            name='tipodispositivo',
            table='equipo_tipo_dispositivo',
        ),
    ]
