# Generated by Django 6.0.5 on 2026-06-22 17:03

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_biomedicos', '0008_remove_dispositivo_bio_disp_frecuencia_positiva_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dispositivo',
            name='bio_disp_costo_no_negativo',
        ),
        migrations.RemoveConstraint(
            model_name='dispositivo',
            name='bio_disp_garantia_fecha_valida',
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='costo_adquisicion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.CheckConstraint(condition=models.Q(('costo_adquisicion__isnull', True), ('costo_adquisicion__gte', 0), _connector='OR'), name='bio_disp_costo_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.CheckConstraint(condition=models.Q(('fin_garantia__isnull', True), ('fecha_instalacion__isnull', True), ('fin_garantia__gte', models.F('fecha_instalacion')), _connector='OR'), name='bio_disp_garantia_fecha_valida'),
        ),
    ]
