# Generated by Django 6.0.5 on 2026-06-23 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_biomedicos', '0009_remove_dispositivo_bio_disp_costo_no_negativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_baja', models.DateField(verbose_name='Fecha de baja')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo de baja')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='baja', to='equipos_biomedicos.dispositivo')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas_dispositivos_biomedicos_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baja de equipo',
                'verbose_name_plural': 'Bajas de equipos',
                'db_table': 'equipo_baja_dispositivo',
                'ordering': ['-fecha_baja', '-fecha_registro'],
            },
        ),
    ]
