# Generated by Django 6.0.5 on 2026-07-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_biomedicos', '0014_seed_colores_dispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Operativo'), (2, 'En mantenimiento'), (3, 'Fuera de servicio'), (4, 'Dado de baja'), (5, 'Repuesto pendiente')], db_index=True, default=1),
        ),
    ]
