# Generated by Django 6.0.5 on 2026-07-02 15:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_biomedicos', '0014_seed_colores_dispositivo'),
        ('rrhh', '0003_remove_personalsalud_area_atencion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'repuesto',
                'verbose_name_plural': 'repuestos',
                'db_table': 'equipo_repuesto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.PositiveSmallIntegerField(choices=[(1, 'Preventivo'), (2, 'Correctivo'), (3, 'Emergencia')], db_index=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Programado'), (2, 'En proceso'), (3, 'Completado'), (4, 'Cancelado')], db_index=True, default=1)),
                ('fecha_solicitud', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('duracion_estimada_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('duracion_real_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion_solicitud', models.TextField()),
                ('trabajo_realizado', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado_final_equipo', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Operativo'), (3, 'Fuera de servicio')], null=True)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_equipos_creados', to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='equipos_biomedicos.dispositivo')),
                ('tecnico_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_equipos_responsable', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'mantenimiento de equipo',
                'verbose_name_plural': 'mantenimientos de equipos',
                'db_table': 'equipo_mantenimiento',
                'ordering': ['-fecha_solicitud', '-fecha_creado'],
            },
        ),
        migrations.CreateModel(
            name='RepuestoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('observaciones', models.CharField(blank=True, max_length=250)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repuestos_usados', to='equipos_biomedicos.mantenimientoequipo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_mantenimiento', to='equipos_biomedicos.repuesto')),
            ],
            options={
                'verbose_name': 'repuesto usado en mantenimiento',
                'verbose_name_plural': 'repuestos usados en mantenimientos',
                'db_table': 'equipo_repuesto_mantenimiento',
                'ordering': ['repuesto__nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='mantenimientoequipo',
            index=models.Index(fields=['dispositivo', 'estado'], name='equipo_mant_disp_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimientoequipo',
            index=models.Index(fields=['estado', 'fecha_solicitud'], name='equipo_mant_estado_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='repuestomantenimiento',
            constraint=models.UniqueConstraint(fields=('mantenimiento', 'repuesto'), name='equipo_repuesto_unico_por_mantenimiento'),
        ),
    ]
