# Generated by Django 5.2.4 on 2026-07-27 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_biomedicos', '0017_bajadispositivo_comentario_responsable_and_more'),
        ('rrhh', '0003_remove_personalsalud_area_atencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajadispositivo',
            name='habitacion_estancia',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Habitación o estancia'),
        ),
        migrations.AddField(
            model_name='bajadispositivo',
            name='responsable_peticion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bajas_dispositivos_biomedicos_solicitadas', to='rrhh.empleado', verbose_name='Responsable de la petición'),
        ),
    ]
