# Generated by Django 5.2.4 on 2026-05-29 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinico', '0004_tipo_atencion_nombre_corto_tipo_atencion'),
        ('rrhh', '0005_personalsalud_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo_laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha Editado')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_creados', to=settings.AUTH_USER_MODEL)),
                ('jornada_laboral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.jornada_laboral')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_modificados', to=settings.AUTH_USER_MODEL)),
                ('personal_salud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.personalsalud')),
            ],
            options={
                'verbose_name': 'Periodo laboral',
                'verbose_name_plural': 'Periodos laborales',
                'ordering': ['personal_salud__empleado'],
            },
        ),
        migrations.CreateModel(
            name='Dia_laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'LUNES'), (2, 'MARTES'), (3, 'MIÉRCOLES'), (4, 'JUEVES'), (5, 'VIERNES'), (6, 'SÁBADO'), (7, 'DOMINGO')], db_index=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('periodo_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_laborales', to='agenda_medica.periodo_laboral')),
            ],
            options={
                'verbose_name': 'Dia laboral',
                'verbose_name_plural': 'Dias laborales',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='Configuracion_cupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupos', models.PositiveSmallIntegerField(verbose_name='Cupos')),
                ('duracion_minutos', models.PositiveSmallIntegerField()),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('tipo_atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinico.tipo_atencion', verbose_name='Tipo Atencion')),
                ('dia_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos', to='agenda_medica.dia_laboral', verbose_name='Dia laboral')),
            ],
            options={
                'verbose_name': 'Configuracion cupo',
                'verbose_name_plural': 'Configuracion cupos',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['estado'], name='agenda_medi_estado_4668b2_idx')],
                'unique_together': {('dia_laboral', 'tipo_atencion')},
            },
        ),
        migrations.AddIndex(
            model_name='periodo_laboral',
            index=models.Index(fields=['estado'], name='agenda_medi_estado_116750_idx'),
        ),
        migrations.AddIndex(
            model_name='periodo_laboral',
            index=models.Index(fields=['estado', 'fecha_inicio'], name='agenda_medi_estado_95a56c_idx'),
        ),
        migrations.AddIndex(
            model_name='periodo_laboral',
            index=models.Index(fields=['personal_salud', 'fecha_inicio'], name='agenda_medi_persona_abc706_idx'),
        ),
        migrations.AddIndex(
            model_name='dia_laboral',
            index=models.Index(fields=['estado'], name='agenda_medi_estado_8d54e4_idx'),
        ),
        migrations.AddIndex(
            model_name='dia_laboral',
            index=models.Index(fields=['periodo_laboral', 'dia_semana'], name='agenda_medi_periodo_c783ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dia_laboral',
            unique_together={('periodo_laboral', 'dia_semana')},
        ),
    ]
