# Generated by Django 5.2.4 on 2026-05-20 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_medica', '0001_initial'),
        ('rrhh', '0005_personalsalud_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='periodo_laboral',
            index=models.Index(fields=['estado', 'fecha_inicio'], name='agenda_medi_estado_95a56c_idx'),
        ),
    ]
