# Generated by Django 5.2.4 on 2026-06-01 20:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_medica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dia_laboral',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dia_laboral_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dia_laboral',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dia_laboral',
            name='fecha_modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Editado'),
        ),
        migrations.AddField(
            model_name='dia_laboral',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dia_laboral_modificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
