# Generated by Django 5.2.4 on 2026-06-01 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_medica', '0002_dia_laboral_creado_por_dia_laboral_fecha_creado_and_more'),
        ('clinico', '0004_tipo_atencion_nombre_corto_tipo_atencion'),
        ('rrhh', '0005_personalsalud_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('tipo', models.SmallIntegerField(choices=[(1, 'VACACIONES'), (2, 'INCAPACIDAD'), (3, 'PERMISO'), (4, 'CAPACITACIÓN'), (5, 'CONGRESO'), (6, 'OTROS')])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha Editado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ausencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ausencias_modificadas', to=settings.AUTH_USER_MODEL)),
                ('personal_salud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ausencias', to='rrhh.personalsalud')),
            ],
            options={
                'verbose_name': 'Ausencia',
                'verbose_name_plural': 'Ausencias',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Cupo_agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha cupo')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.SmallIntegerField(choices=[(1, 'DISPONIBLE'), (2, 'ASIGNADO'), (3, 'BLOQUEADO'), (4, 'INACTIVO')], default=1)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha Editado')),
                ('ausencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cupos_afectados', to='agenda_medica.ausencia')),
                ('configuracion_cupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cupos_agenda', to='agenda_medica.configuracion_cupo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cupos_agenda_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cupos_agenda_modificados', to=settings.AUTH_USER_MODEL)),
                ('personal_salud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cupos_agenda', to='rrhh.personalsalud')),
                ('tipo_atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cupos_agenda', to='clinico.tipo_atencion')),
            ],
            options={
                'verbose_name': 'Cupo agenda',
                'verbose_name_plural': 'Cupos agenda',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='ausencia',
            index=models.Index(fields=['estado'], name='agenda_medi_estado_0ba3e0_idx'),
        ),
        migrations.AddIndex(
            model_name='ausencia',
            index=models.Index(fields=['personal_salud'], name='agenda_medi_persona_51c9af_idx'),
        ),
        migrations.AddIndex(
            model_name='ausencia',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='agenda_medi_fecha_i_6048fe_idx'),
        ),
        migrations.AddIndex(
            model_name='cupo_agenda',
            index=models.Index(fields=['estado'], name='agenda_medi_estado_058240_idx'),
        ),
        migrations.AddIndex(
            model_name='cupo_agenda',
            index=models.Index(fields=['fecha'], name='agenda_medi_fecha_078c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='cupo_agenda',
            index=models.Index(fields=['personal_salud', 'fecha'], name='agenda_medi_persona_777f97_idx'),
        ),
        migrations.AddIndex(
            model_name='cupo_agenda',
            index=models.Index(fields=['tipo_atencion', 'fecha'], name='agenda_medi_tipo_at_a04cfb_idx'),
        ),
    ]
