# Generated by Django 5.2.4 on 2026-07-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_medica', '0003_ausencia_cupo_agenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion_cupo',
            name='orden',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
