# Generated by Django 5.2.4 on 2026-08-28 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_medica', '0004_configuracion_cupo_orden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia_quirurgico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha Editado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dias_quirurgicos_creados', to=settings.AUTH_USER_MODEL)),
                ('dia_laboral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dia_quirurgico', to='agenda_medica.dia_laboral')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dias_quirurgicos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dia quirurgico',
                'verbose_name_plural': 'Dias quirurgicos',
                'ordering': ['dia_laboral__dia_semana'],
                'indexes': [models.Index(fields=['estado'], name='agenda_medi_estado_c6eee3_idx')],
            },
        ),
    ]
