# Generated by Django 5.2.4 on 2026-09-07 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_medica', '0005_dia_quirurgico'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dia_laboral',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='configuracion_cupo',
            name='dia_laboral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_cupo', to='agenda_medica.dia_laboral', verbose_name='Dia laboral'),
        ),
    ]
